import { useSim } from "@/lib/sim/store";
import { patientById } from "@/lib/sim/patients";
import { projectionById } from "@/lib/sim/projections";
import { classifyEI } from "@/lib/sim/exposure";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Slider } from "@/components/ui/slider";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import type { ReactNode } from "react";
function Row({label,value,children}:{label:string;value:string;children:ReactNode}){return <div className="space-y-1.5"><div className="flex items-baseline justify-between gap-2"><Label>{label}</Label><span className="font-mono text-xs tabular-nums text-fg">{value}</span></div>{children}</div>}
function ExamStep({children}:{children:ReactNode}){return <div className="rounded-md border border-border bg-elevated p-3 text-xs leading-relaxed text-muted">{children}</div>}
export function ControlDeck(){
 const pose=useSim(s=>s.pose),tube=useSim(s=>s.tube),exposure=useSim(s=>s.exposure),equipment=useSim(s=>s.equipment),mode=useSim(s=>s.mode),patientId=useSim(s=>s.patientId),projectionId=useSim(s=>s.projectionId),showLandmarks=useSim(s=>s.showLandmarks),showLightField=useSim(s=>s.showLightField),preparing=useSim(s=>s.preparing),exposing=useSim(s=>s.exposing);const patchPose=useSim(s=>s.patchPose),patchTube=useSim(s=>s.patchTube),patchExposure=useSim(s=>s.patchExposure),patchEquipment=useSim(s=>s.patchEquipment),applyHandbook=useSim(s=>s.applyHandbook),applySuggestedFactors=useSim(s=>s.applySuggestedFactors),setShowLandmarks=useSim(s=>s.setShowLandmarks),setShowLightField=useSim(s=>s.setShowLightField),predictedEI=useSim(s=>s.predictedEI),prepare=useSim(s=>s.prepare),expose=useSim(s=>s.expose);const patient=patientById(patientId),projection=projectionById(projectionId),ei=predictedEI(),eiStatus=classifyEI(ei);const isChest=projection.id.includes('chest'),isUpper=projection.region==='Upper limb',isLower=projection.region==='Lower limb',isPelvis=projection.region==='Pelvis & hips';
 return <div className="flex h-full flex-col gap-3 overflow-hidden"><div className="flex items-start justify-between gap-2"><div><p className="text-xs text-muted">{projection.region}</p><h2 className="text-base font-medium leading-snug">{projection.name}</h2></div><Badge tone={mode==='practice'?'accent':'warn'}>{mode}</Badge></div><Tabs defaultValue="position" className="flex min-h-0 flex-1 flex-col"><TabsList><TabsTrigger value="position">Position</TabsTrigger><TabsTrigger value="room">Room</TabsTrigger><TabsTrigger value="beam">Beam</TabsTrigger><TabsTrigger value="expose">Expose</TabsTrigger></TabsList><div className="min-h-0 flex-1 overflow-y-auto pr-1">
 <TabsContent value="position" className="space-y-4"><ExamStep><strong className="text-fg">Positioning instruction</strong><br/>{projection.position}</ExamStep><div className="flex flex-wrap gap-2"><Button size="sm" onClick={applyHandbook}>Set standard position</Button>{projection.recumbency==='erect'&&<Button size="sm" variant="outline" onClick={()=>patchPose({recumbency:'erect'})}>Erect</Button>}{projection.recumbency==='supine'&&<Button size="sm" variant="outline" onClick={()=>patchPose({recumbency:'supine'})}>Supine</Button>}{isUpper&&<Button size="sm" variant="outline" onClick={()=>patchPose({rotationY:0})}>AP/PA</Button>}{isUpper&&<Button size="sm" variant="outline" onClick={()=>patchPose({rotationY:90})}>Lateral</Button>}</div>
 {isChest&&<><Row label="Patient rotation" value={`${pose.rotationY.toFixed(0)}°`}><Slider min={-15} max={15} step={1} value={[pose.rotationY]} onValueChange={([v])=>patchPose({rotationY:v??0})}/></Row><Row label="Shoulder roll / scapulae clearance" value={`${Math.round(pose.shoulderRoll*100)}%`}><Slider min={0} max={1} step={.05} value={[pose.shoulderRoll]} onValueChange={([v])=>patchPose({shoulderRoll:v??0})}/></Row><Row label="Arm elevation" value={`${Math.round(pose.armRaise*100)}%`}><Slider min={0} max={1} step={.05} value={[pose.armRaise]} onValueChange={([v])=>patchPose({armRaise:v??0})}/></Row></>}
 {(projection.id.includes('cspine')||projection.id.includes('skull'))&&<Row label="Chin position" value={`${Math.round(pose.chinUp*100)}%`}><Slider min={0} max={1} step={.05} value={[pose.chinUp]} onValueChange={([v])=>patchPose({chinUp:v??0})}/></Row>}
 {(projection.id.includes('shoulder')||projection.id.includes('elbow')||projection.id.includes('wrist')||projection.id.includes('hand'))&&<><Row label="Arm elevation" value={`${Math.round(pose.armRaise*100)}%`}><Slider min={0} max={1} step={.05} value={[pose.armRaise]} onValueChange={([v])=>patchPose({armRaise:v??0})}/></Row><Row label="Elbow flexion" value={`${pose.elbowFlex.toFixed(0)}°`}><Slider min={0} max={140} step={1} value={[pose.elbowFlex]} onValueChange={([v])=>patchPose({elbowFlex:v??0})}/></Row></>}
 {(isLower||isPelvis)&&<Row label="Knee flexion" value={`${pose.kneeFlex.toFixed(0)}°`}><Slider min={0} max={120} step={1} value={[pose.kneeFlex]} onValueChange={([v])=>patchPose({kneeFlex:v??0})}/></Row>}
 {isPelvis&&<Row label="Leg internal rotation" value={`${pose.hipInternal.toFixed(0)}°`}><Slider min={0} max={30} step={1} value={[pose.hipInternal]} onValueChange={([v])=>patchPose({hipInternal:v??0})}/></Row>}
 {(projection.region==='Thorax'||projection.region==='Abdomen')&&<div><Label>Breathing instruction</Label><div className="mt-2 flex gap-2"><Button size="sm" variant={pose.breath==='inspiration'?'default':'outline'} onClick={()=>patchPose({breath:'inspiration'})}>Inspiration</Button><Button size="sm" variant={pose.breath==='expiration'?'default':'outline'} onClick={()=>patchPose({breath:'expiration'})}>Expiration</Button></div></div>}<Button size="sm" variant="outline" className="w-full" onClick={applyHandbook}>Return to standard exam position</Button></TabsContent>
 <TabsContent value="room" className="space-y-4"><ExamStep><strong className="text-fg">Room setup</strong><br/>Move the patient and detector relationship first. The tube should follow the detector when locked. For a real exam, align the anatomy to the IR before fine-tuning the central ray.</ExamStep><Button size="sm" variant={tube.lockedToDetector?'default':'outline'} onClick={()=>patchTube({lockedToDetector:!tube.lockedToDetector})}>Tube {tube.lockedToDetector?'LOCKED to IR':'FREE'}</Button><Row label="Patient lateral shift" value={`${equipment.patientX.toFixed(2)} m`}><Slider min={-.4} max={.4} step={.01} value={[equipment.patientX]} onValueChange={([v])=>patchEquipment({patientX:v??0})}/></Row><Row label="Patient vertical shift" value={`${equipment.patientY.toFixed(2)} m`}><Slider min={-.5} max={.5} step={.01} value={[equipment.patientY]} onValueChange={([v])=>patchEquipment({patientY:v??0})}/></Row><Row label="Patient longitudinal shift" value={`${equipment.patientZ.toFixed(2)} m`}><Slider min={-.4} max={.4} step={.01} value={[equipment.patientZ]} onValueChange={([v])=>patchEquipment({patientZ:v??0})}/></Row>{equipment.placement==='table'&&<><Separator/><p className="text-[11px] uppercase tracking-wider text-muted">Table</p><Row label="Table height" value={`${equipment.tableHeight.toFixed(2)} m`}><Slider min={.55} max={1.2} step={.01} value={[equipment.tableHeight]} onValueChange={([v])=>patchEquipment({tableHeight:v??.9})}/></Row><Row label="Table lateral" value={`${equipment.tableX.toFixed(2)} m`}><Slider min={-.5} max={.5} step={.01} value={[equipment.tableX]} onValueChange={([v])=>patchEquipment({tableX:v??0})}/></Row><Row label="Table longitudinal" value={`${equipment.tableZ.toFixed(2)} m`}><Slider min={-.6} max={.6} step={.01} value={[equipment.tableZ]} onValueChange={([v])=>patchEquipment({tableZ:v??0})}/></Row></>}{(equipment.placement==='upright-bucky'||equipment.placement==='standing'||equipment.placement==='seated')&&<><Separator/><p className="text-[11px] uppercase tracking-wider text-muted">Upright detector</p><Row label="IR height" value={`${equipment.buckyHeight.toFixed(2)} m`}><Slider min={.4} max={1.8} step={.01} value={[equipment.buckyHeight]} onValueChange={([v])=>patchEquipment({buckyHeight:v??1.1})}/></Row><Row label="IR tilt" value={`${equipment.buckyTilt.toFixed(0)}°`}><Slider min={0} max={90} step={1} value={[equipment.buckyTilt]} onValueChange={([v])=>patchEquipment({buckyTilt:v??0})}/></Row></>}</TabsContent>
 <TabsContent value="beam" className="space-y-4"><ExamStep><strong className="text-fg">Beam instruction</strong><br/>{projection.beam}</ExamStep><div className="flex flex-wrap gap-2"><Button size="sm" variant={showLightField?'default':'outline'} onClick={()=>setShowLightField(!showLightField)}>Light field {showLightField?'ON':'OFF'}</Button><Button size="sm" variant={showLandmarks?'default':'outline'} onClick={()=>setShowLandmarks(!showLandmarks)}>Landmarks {showLandmarks?'ON':'OFF'}</Button></div><Row label="CR height" value={`${tube.crY.toFixed(1)} cm`}><Slider min={0} max={patient.heightCm} step={.5} value={[tube.crY]} onValueChange={([v])=>patchTube({crY:v??40})}/></Row><Row label="CR lateral" value={`${tube.crX.toFixed(1)} cm`}><Slider min={-20} max={20} step={.5} value={[tube.crX]} onValueChange={([v])=>patchTube({crX:v??0})}/></Row><Row label="SID / FFD" value={`${tube.sid.toFixed(0)} cm`}><Slider min={80} max={200} step={1} value={[tube.sid]} onValueChange={([v])=>patchTube({sid:v??100})}/></Row><Row label="Tube angulation" value={`${tube.angle.toFixed(0)}°`}><Slider min={-30} max={30} step={1} value={[tube.angle]} onValueChange={([v])=>patchTube({angle:v??0})}/></Row><Row label="Collimation width" value={`${tube.collimationW.toFixed(1)} cm`}><Slider min={5} max={45} step={.5} value={[tube.collimationW]} onValueChange={([v])=>patchTube({collimationW:v??20})}/></Row><Row label="Collimation height" value={`${tube.collimationH.toFixed(1)} cm`}><Slider min={5} max={45} step={.5} value={[tube.collimationH]} onValueChange={([v])=>patchTube({collimationH:v??20})}/></Row><Button size="sm" variant="outline" className="w-full" onClick={()=>{patchTube({crX:projection.cr.x*(projection.anatomy.startsWith('torso')?patient.morph.torsoWidth:1),crY:projection.cr.y});applyHandbook()}}>Centre to exam</Button></TabsContent>
 <TabsContent value="expose" className="space-y-4"><ExamStep><strong className="text-fg">Exposure sequence</strong><br/>Set the patient position, IR and beam first. Then select technique, prepare the tube, and expose only when the positioning is ready.</ExamStep><div className="rounded-md border border-border bg-elevated p-3 text-xs"><p className="text-muted">Predicted EI</p><p className="mt-1 font-mono text-lg tabular-nums text-fg">{ei.toFixed(0)}</p><p className="mt-1 text-muted">Status: <span className="text-fg">{eiStatus}</span></p></div><Row label="kVp" value={`${exposure.kvp}`}><Slider min={40} max={125} step={1} value={[exposure.kvp]} onValueChange={([v])=>patchExposure({kvp:v??70})}/></Row><Row label="mAs" value={exposure.mas<10?exposure.mas.toFixed(1):exposure.mas.toFixed(0)}><Slider min={.5} max={100} step={.5} value={[exposure.mas]} onValueChange={([v])=>patchExposure({mas:v??2})}/></Row><div className="flex flex-wrap gap-2"><Button size="sm" variant={exposure.grid?'default':'outline'} onClick={()=>patchExposure({grid:!exposure.grid})}>Grid {exposure.grid?'IN':'OUT'}</Button><Button size="sm" variant={exposure.focalSpot==='fine'?'default':'outline'} onClick={()=>patchExposure({focalSpot:exposure.focalSpot==='fine'?'broad':'fine'})}>{exposure.focalSpot} focus</Button><Button size="sm" variant={exposure.marker==='L'?'default':'outline'} onClick={()=>patchExposure({marker:exposure.marker==='L'?null:'L'})}>L marker</Button><Button size="sm" variant={exposure.marker==='R'?'default':'outline'} onClick={()=>patchExposure({marker:exposure.marker==='R'?null:'R'})}>R marker</Button></div><Button size="sm" variant="outline" className="w-full" onClick={applySuggestedFactors}>Load standard technique</Button><Separator/><div className="grid grid-cols-2 gap-2"><Button variant="outline" size="lg" onClick={prepare} disabled={preparing||exposing}>{preparing?'Rotor up':'Prepare'}</Button><Button variant="solid" size="lg" onClick={()=>void expose()} disabled={exposing}>{exposing?'Exposing':'Expose'}</Button></div></TabsContent>
 </div></Tabs></div>;
}