import { useMemo, useState } from "react";
import { REQUEST_BANK } from "@/lib/sim/request-bank";
import type { ImagingRequest } from "@/lib/sim/requests";
import { patientById } from "@/lib/sim/patients";
import { requestSpecificity } from "@/lib/sim/request-specificity";
import { useSim } from "@/lib/sim/store";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const PAGE_SIZE = 15;
export function Library() {
  const mode=useSim(s=>s.mode); const setMode=useSim(s=>s.setMode); const startExam=useSim(s=>s.startExam); const completed=useSim(s=>s.completedRequestIds); const resetRequests=useSim(s=>s.resetRequests); const startNextRequest=useSim(s=>s.startNextRequest); const completeRequestById=useSim(s=>s.completeRequestById);
  const [selectedId,setSelectedId]=useState<string|null>(null); const [page,setPage]=useState(0); const [popup,setPopup]=useState<{title:string;message:string}|null>(null);
  const pageCount=Math.ceil(REQUEST_BANK.length/PAGE_SIZE); const pageRequests=useMemo(()=>REQUEST_BANK.slice(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE),[page]); const selected=REQUEST_BANK.find(r=>r.id===selectedId)??pageRequests[0]??null; const allDone=completed.length>=REQUEST_BANK.length; const remaining=REQUEST_BANK.length-completed.length;
  const specificity=selected?requestSpecificity(selected):null;
  function handleAccept(req:ImagingRequest){ if(completed.includes(req.id))return; if(!req.isValid){setPopup({title:"Request is not correct",message:req.rejectionReason??"This request is not appropriate as written."});return;} startExam(req.requestedProjections[0]??"pa-chest",req.patientId,req.id,0); }
  function handleReject(req:ImagingRequest){ if(req.isValid){setPopup({title:"Do not reject this request",message:"The request is clinically appropriate as written. Continue to examination unless you have a valid reason to query the referrer."});return;} completeRequestById(req.id); setPopup({title:"Correct decision",message:`Correct — this request should be rejected because the laterality or clinical request is incorrect. ${req.rejectionReason??"Amend the request before exposure."}`}); }
  return <div className="min-h-dvh bg-bg">
    <header className="border-b border-border bg-surface px-4 py-4"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold tracking-tight">Bucky Lab</h1><p className="text-sm text-muted">Imaging request vetting · {remaining} requests remaining · {completed.length} completed</p></div><div className="flex items-center gap-2"><Button size="sm" variant={mode==="practice"?"default":"outline"} onClick={()=>setMode("practice")}>Practice</Button><Button size="sm" variant={mode==="assessment"?"default":"outline"} onClick={()=>setMode("assessment")}>Assessment</Button><Button size="sm" variant="outline" onClick={resetRequests}>Reset</Button></div></div></header>
    <div className="mx-auto max-w-6xl px-4 py-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-surface px-4 py-3"><div className="text-sm"><span className="font-medium">Request bank:</span> {REQUEST_BANK.length} unique scenarios · 15 shown at a time</div>{!allDone?<Button size="sm" onClick={startNextRequest}>Generate next request</Button>:<Button size="sm" onClick={resetRequests}>Start new run</Button>}</div>
      <div className="grid gap-5 lg:grid-cols-[1fr_380px]"><section><div className="mb-3 flex items-center justify-between"><p className="text-sm text-muted">Page {page+1} of {pageCount}</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))}>Previous</Button><Button size="sm" variant="outline" disabled={page>=pageCount-1} onClick={()=>setPage(p=>Math.min(pageCount-1,p+1))}>Next</Button></div></div><div className="space-y-2">{pageRequests.map(req=>{const active=req.id===selected?.id;const done=completed.includes(req.id);const detail=requestSpecificity(req);return <button key={req.id} type="button" onClick={()=>setSelectedId(req.id)} className={`w-full rounded-lg border px-4 py-3 text-left transition-colors ${active?"border-accent bg-accent/10":"border-border bg-surface hover:border-muted"} ${done?"opacity-55":""}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="font-medium text-fg">{req.title}</p><p className="mt-0.5 truncate text-xs text-muted">{req.requestedViewsLabel}</p><p className="mt-1 text-[11px] text-muted">{detail.laterality} · {detail.extent} · {detail.anatomy}</p></div><div className="flex shrink-0 items-center gap-1"><Badge tone={done?"ok":req.isValid?"muted":"danger"}>{done?"Completed":req.isValid?"Valid":"Query"}</Badge><Badge tone="muted">{req.id.replace("req-","#")}</Badge></div></div></button>})}</div></section>
        <aside className="rounded-lg border border-border bg-surface p-5 lg:sticky lg:top-5 lg:h-fit">{selected&&specificity?<><p className="text-[11px] font-medium uppercase tracking-wider text-muted">Request detail</p><h3 className="mt-1 text-lg font-medium">{selected.title}</h3><div className="mt-4 space-y-3 text-sm"><div><p className="text-[11px] uppercase tracking-wider text-muted">Clinical history</p><p className="mt-1 leading-relaxed">{selected.clinicalHistory}</p></div><div><p className="text-[11px] uppercase tracking-wider text-muted">Requested examination</p><p className="mt-1 font-medium">{selected.requestedViewsLabel}</p></div><div className="rounded-md border border-accent/30 bg-accent/5 p-3"><p className="text-[11px] font-medium uppercase tracking-wider text-muted">Area-of-interest check</p><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><div><span className="text-muted">Side</span><p className="font-medium text-fg">{specificity.laterality}</p></div><div><span className="text-muted">Extent</span><p className="font-medium text-fg">{specificity.extent}</p></div><div className="col-span-2"><span className="text-muted">Anatomy</span><p className="font-medium text-fg">{specificity.anatomy}</p></div><div className="col-span-2"><span className="text-muted">Surface</span><p className="font-medium text-fg">{specificity.surface}</p></div></div><p className="mt-3 text-[11px] leading-relaxed text-muted">{specificity.confirmationPrompt}</p></div><div><p className="text-[11px] uppercase tracking-wider text-muted">Patient</p><p className="mt-1">{patientById(selected.patientId).name} · {patientById(selected.patientId).age} years · {patientById(selected.patientId).habitus}</p></div></div><div className="mt-6 grid gap-2"><Button variant="solid" className="w-full" disabled={completed.includes(selected.id)} onClick={()=>handleAccept(selected)}>{completed.includes(selected.id)?"Completed":"Accept & start examination"}</Button><Button variant="outline" className="w-full" disabled={completed.includes(selected.id)} onClick={()=>handleReject(selected)}>Reject / query request</Button></div></>:<p className="text-sm text-muted">Select a request to review it.</p>}</aside>
      </div></div>
      {popup?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-xl border border-border bg-surface p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] uppercase tracking-wider text-muted">Vetting feedback</p><h2 className="mt-1 text-lg font-semibold">{popup.title}</h2></div><Button size="sm" variant="ghost" onClick={()=>setPopup(null)}>Close</Button></div><p className="mt-4 text-sm leading-relaxed text-fg">{popup.message}</p><div className="mt-6 flex justify-end"><Button onClick={()=>{setPopup(null);if(!allDone)startNextRequest();}}>Understood</Button></div></div></div>:null}
  </div>;
}
