import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowLeft, ScanLine, Zap } from "lucide-react";
import { PROJECTIONS } from "@/lib/sim/projections";
import { patientById } from "@/lib/sim/patients";
import { useSim } from "@/lib/sim/store";
import { renderRadiograph } from "@/lib/sim/render-radiograph";
import { Button } from "@/components/ui/button";

const TEST_PATIENT = "amara";
const TEST_RENDER_HEIGHT = 384;
const GROUPS = ["Whole body","Thorax","Abdomen","Pelvis & hips","Spine","Upper limb","Lower limb","Skull"];

export function TestExposure() {
  const startExam=useSim(s=>s.startExam),applyHandbook=useSim(s=>s.applyHandbook),applySuggestedFactors=useSim(s=>s.applySuggestedFactors),patchExposure=useSim(s=>s.patchExposure),exposure=useSim(s=>s.exposure),tube=useSim(s=>s.tube),pose=useSim(s=>s.pose),result=useSim(s=>s.result),exposing=useSim(s=>s.exposing),error=useSim(s=>s.error);
  const[selected,setSelected]=useState<string|null>(null),patient=patientById(TEST_PATIENT);
  const grouped=useMemo(()=>GROUPS.map(region=>({region,projections:PROJECTIONS.filter(p=>p.region===region)})).filter(g=>g.projections.length),[]);
  async function test(projectionId:string){if(useSim.getState().exposing)return;setSelected(projectionId);startExam(projectionId,TEST_PATIENT);applyHandbook();applySuggestedFactors();patchExposure({marker:null});const s=useSim.getState();useSim.setState({exposing:true,error:null,preparing:false});try{const benchmark=await renderRadiograph({patient:patientById(s.patientId),projection:PROJECTIONS.find(p=>p.id===s.projectionId)!,pose:s.pose,tube:s.tube,exposure:s.exposure,pathologyId:"none",caseId:null,height:TEST_RENDER_HEIGHT});useSim.setState({result:benchmark,exposing:false});}catch(err){useSim.setState({exposing:false,error:err instanceof Error?err.message:"Exposure failed"});}}
  const selectedProjection=selected?PROJECTIONS.find(p=>p.id===selected):undefined;
  return <div className="min-h-dvh bg-bg text-foreground">
   <header className="sticky top-0 z-10 flex items-center gap-3 border-b border-border bg-surface/95 px-4 py-3 backdrop-blur"><Link to="/cases"><Button variant="ghost" size="sm" className="gap-1.5"><ArrowLeft className="size-4"/>Case library</Button></Link><div className="min-w-0 flex-1"><h1 className="text-base font-semibold">Imaging test bench</h1><p className="text-xs text-muted">Radiography benchmark + advanced CT protocol testing</p></div><Link to="/ct"><Button variant="outline" size="sm" className="gap-1.5"><ScanLine className="size-4"/>CT test mode</Button></Link><span className="rounded border border-border px-2 py-1 text-[10px] font-semibold tracking-wide text-muted">TEST MODE</span></header>
   <main className="mx-auto grid max-w-7xl gap-5 p-4 lg:grid-cols-[minmax(0,1fr)_420px]">
    <section className="rounded-xl border border-border bg-panel p-4"><div className="mb-4 rounded-lg border border-border bg-surface p-3 text-sm"><div className="font-medium">Fixed benchmark patient</div><div className="mt-1 text-xs text-muted">{patient.name} · {patient.habitus} · {patient.heightCm} cm · pathology disabled</div><div className="mt-2 text-xs leading-5 text-muted">Radiography uses a reduced detector matrix for fast iteration. Use CT test mode for the dedicated CT case/protocol library and contrast-phase presets.</div></div><div className="space-y-5">{grouped.map(group=><div key={group.region}><h2 className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted">{group.region}</h2><div className="grid gap-2 sm:grid-cols-2">{group.projections.map(projection=>{const active=selected===projection.id&&exposing;return <Button key={projection.id} variant={selected===projection.id?"default":"outline"} className="h-auto min-h-20 justify-between gap-3 px-3 py-2 text-left" disabled={exposing} onClick={()=>void test(projection.id)}><span className="min-w-0"><span className="block truncate text-sm font-medium">{projection.name}</span><span className="mt-0.5 block text-[11px] opacity-70">{projection.sidCm} cm SID · {projection.collimationW} × {projection.collimationH} cm</span><span className="mt-0.5 block text-[11px] opacity-70">{projection.grid?"Grid":"No grid"} · {projection.kvp} kVp · {projection.mas} mAs reference</span></span><Zap className={`size-4 shrink-0 ${active?"animate-pulse":""}`}/></Button>})}</div></div>)}</div></section>
    <aside className="rounded-xl border border-border bg-panel p-4 lg:sticky lg:top-20 lg:h-fit"><h2 className="font-semibold">Test result</h2>{selectedProjection?<div className="mt-3 space-y-3 text-sm"><div className="rounded-lg border border-border bg-surface p-3"><div className="font-medium">{selectedProjection.name}</div><div className="mt-1 text-xs text-muted">{exposing?"Rendering fast preview…":result?"Exposure complete":"Preparing…"}</div></div>{result?.dataUrl?<div className="overflow-hidden rounded-lg border border-border bg-black"><img src={result.dataUrl} alt={`${selectedProjection.name} benchmark radiograph`} className="block h-auto w-full"/></div>:null}<div className="grid grid-cols-2 gap-2 text-xs"><div className="rounded border border-border p-2"><span className="text-muted">kVp</span><div className="font-semibold">{exposure.kvp}</div></div><div className="rounded border border-border p-2"><span className="text-muted">mAs</span><div className="font-semibold">{exposure.mas}</div></div><div className="rounded border border-border p-2"><span className="text-muted">Grid</span><div className="font-semibold">{exposure.grid?"Applied":"Not required"}</div></div><div className="rounded border border-border p-2"><span className="text-muted">SID</span><div className="font-semibold">{tube.sid} cm</div></div><div className="rounded border border-border p-2"><span className="text-muted">Collimation</span><div className="font-semibold">{tube.collimationW} × {tube.collimationH} cm</div></div><div className="rounded border border-border p-2"><span className="text-muted">Breathing</span><div className="font-semibold capitalize">{pose.breath}</div></div></div>{error?<div className="rounded border border-destructive/40 bg-destructive/10 p-3 text-xs text-destructive">{error}</div>:null}</div>:<p className="mt-2 text-xs text-muted">Choose a projection, or open CT test mode for advanced imaging.</p>}</aside>
   </main>
  </div>;
}
