export type CtPhase="non-contrast"|"arterial"|"portal-venous"|"delayed"|"split-bolus-bastion";
export interface CtPhasePreset{id:CtPhase;name:string;delay:string;purpose:string;}
export interface CtProtocol{id:string;name:string;category:string;coverage:string;defaultPhase:CtPhase;availablePhases:CtPhase[];summary:string;reconstructions:string[];contrast:string;}

export const CT_PHASES:Record<CtPhase,CtPhasePreset>={
 "non-contrast":{id:"non-contrast",name:"Non-contrast",delay:"No IV contrast",purpose:"Baseline attenuation, haemorrhage, calcification and selected stone/head examinations."},
 arterial:{id:"arterial",name:"Arterial phase",delay:"Approx. 20–35 s / bolus triggered",purpose:"Arterial enhancement, active haemorrhage and vascular assessment."},
 "portal-venous":{id:"portal-venous",name:"Portal venous phase",delay:"Approx. 60–75 s",purpose:"Routine abdominal solid-organ and venous enhancement."},
 delayed:{id:"delayed",name:"Delayed phase",delay:"Protocol dependent, typically minutes",purpose:"Selected urinary, vascular, bleeding and lesion-characterisation questions."},
 "split-bolus-bastion":{id:"split-bolus-bastion",name:"Split-bolus trauma (Camp Bastion style)",delay:"Single acquisition after slow venous + faster arterial bolus",purpose:"Combined arterial and portal-venous enhancement in a single trauma acquisition."},
};

/** Educational presets model common UK/NHS practice; exact local trust protocols vary. */
export const CT_PROTOCOLS:CtProtocol[]=[
 {id:"ct-head",name:"CT Head",category:"Neuro",coverage:"Vertex to skull base",defaultPhase:"non-contrast",availablePhases:["non-contrast","arterial","delayed"],summary:"Acute head assessment with non-contrast as the standard starting acquisition; contrast/angiographic phases selected by indication.",reconstructions:["Axial brain","Thin axial","Coronal MPR","Sagittal MPR","Bone"],contrast:"Usually none for the initial acute head acquisition."},
 {id:"ct-cap",name:"CT Chest Abdomen Pelvis (CAP)",category:"Body",coverage:"Thoracic inlet through symphysis pubis",defaultPhase:"portal-venous",availablePhases:["non-contrast","arterial","portal-venous","delayed"],summary:"General contrast-enhanced body examination with portal-venous imaging as the core abdominal phase; additional phases depend on indication.",reconstructions:["Axial soft tissue","Coronal MPR","Sagittal MPR","Lung","Bone"],contrast:"IV iodinated contrast; dose/rate are patient and local-protocol dependent."},
 {id:"ct-colonography",name:"CT Colonography",category:"Gastrointestinal",coverage:"Colon and abdomen/pelvis",defaultPhase:"non-contrast",availablePhases:["non-contrast","portal-venous"],summary:"Low-dose supine/prone or alternative-position colonic assessment following bowel preparation/tagging and gas insufflation; IV contrast depends on indication/local protocol.",reconstructions:["Thin axial","Coronal MPR","3D endoluminal","Colon dissection view"],contrast:"Oral faecal tagging is typical; IV contrast is protocol/indication dependent."},
 {id:"ct-trauma",name:"Major Trauma CT",category:"Trauma",coverage:"Non-contrast head plus neck/chest/abdomen/pelvis as clinically indicated",defaultPhase:"split-bolus-bastion",availablePhases:["non-contrast","arterial","portal-venous","split-bolus-bastion","delayed"],summary:"Whole-body trauma workflow with a non-contrast head and contrast-enhanced torso. Includes a single-pass split-bolus option based on Camp Bastion/UK major-trauma practice.",reconstructions:["Head brain/bone","C-spine","Chest/abdomen/pelvis soft tissue","Lung","Whole-spine bone MPR","Pelvic bone"],contrast:"Split bolus combines slower portal-venous and faster arterial injections before one acquisition; exact volume/rate must follow local trust policy."},
 {id:"ctpa",name:"CT Pulmonary Angiogram",category:"Cardiothoracic",coverage:"Lung apices through lung bases",defaultPhase:"arterial",availablePhases:["arterial"],summary:"Bolus-timed pulmonary arterial acquisition for suspected pulmonary embolism.",reconstructions:["Thin axial","Coronal MPR","Sagittal MPR","Lung"],contrast:"Rapid IV iodinated contrast with pulmonary-artery bolus tracking."},
 {id:"cta-aorta",name:"CT Aorta / Aortogram",category:"Vascular",coverage:"Aorta with coverage tailored to indication",defaultPhase:"arterial",availablePhases:["non-contrast","arterial","delayed"],summary:"Arterial-phase assessment of aortic pathology with non-contrast or delayed acquisitions when clinically indicated.",reconstructions:["Thin axial","Coronal MPR","Sagittal MPR","MIP","3D vascular"],contrast:"Arterial bolus tracking; parameters vary by scanner, patient and local protocol."},
 {id:"ct-kub",name:"CT KUB",category:"Urinary",coverage:"Kidneys through bladder",defaultPhase:"non-contrast",availablePhases:["non-contrast","delayed"],summary:"Low-dose non-contrast urinary-tract assessment, particularly for calculi; delayed/excretory imaging is a separate indication-dependent acquisition.",reconstructions:["Thin axial","Coronal MPR","Sagittal MPR"],contrast:"None for standard stone CT KUB."},
];
