import * as THREE from "three";
import { useMemo } from "react";
import { patientKinematics, type V3 } from "@/lib/sim/patient-kinematics";

type BoneSpec={a:V3;b:V3;r:number};
function Bone({a,b,radius,opacity}:{a:V3;b:V3;radius:number;opacity:number}){const {position,quaternion,length}=useMemo(()=>{const start=new THREE.Vector3(...a),end=new THREE.Vector3(...b),direction=end.clone().sub(start),length=direction.length();return{position:start.clone().add(end).multiplyScalar(.5),quaternion:new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),direction.normalize()),length};},[a,b]);return <mesh position={position} quaternion={quaternion} renderOrder={10}><capsuleGeometry args={[radius,Math.max(.01,length-radius*2),10,18]}/><meshPhysicalMaterial color="#e8e1cd" transparent opacity={opacity} roughness={.78} depthWrite={false} depthTest={false}/></mesh>}
function Joint({position,radius,opacity}:{position:V3;radius:number;opacity:number}){return <group position={position} renderOrder={11}><mesh><sphereGeometry args={[radius,18,12]}/><meshPhysicalMaterial color="#e8e1cd" transparent opacity={opacity} roughness={.78} depthWrite={false} depthTest={false}/></mesh><mesh scale={[1.12,.72,1.12]}><sphereGeometry args={[radius,14,10]}/><meshPhysicalMaterial color="#d7e1d0" transparent opacity={opacity*.62} roughness={.42} depthWrite={false} depthTest={false}/></mesh></group>}
function FlatBone({position,scale,rotation=[0,0,0] as [number,number,number],opacity}:{position:V3;scale:V3;rotation?:[number,number,number];opacity:number}){return <mesh position={position} scale={scale} rotation={rotation} renderOrder={10}><sphereGeometry args={[1,20,12]}/><meshPhysicalMaterial color="#e8e1cd" transparent opacity={opacity} roughness={.8} depthWrite={false} depthTest={false}/></mesh>}
function vertebra(y:number,s:number,depth:number,index:number):BoneSpec[]{const body=.021*s*(index<5?1.08:.95),ped=.008*s,trans=.012*s,spin=.013*s,z=.015*depth;return[{a:[-.02*s,y,z],b:[.02*s,y,z],r:body},{a:[-.02*s,y,z],b:[-.045*s,y-.004*s,z-.008*s],r:ped},{a:[.02*s,y,z],b:[.045*s,y-.004*s,z-.008*s],r:ped},{a:[-.045*s,y-.004*s,z-.008*s],b:[-.073*s,y+.004*s,z+.006*s],r:trans},{a:[.045*s,y-.004*s,z-.008*s],b:[.073*s,y+.004*s,z+.006*s],r:trans},{a:[-.073*s,y+.004*s,z+.006*s],b:[0,y+.018*s,z+.023*s],r:spin},{a:[.073*s,y+.004*s,z+.006*s],b:[0,y+.018*s,z+.023*s],r:spin}];}
export function BoneJointLayer({H,s,torsoWidth,torsoDepth,shoulder,hip,patientMorph,pose,projectionId,placement,buckyTilt,opacity}:{H:number;s:number;torsoWidth:number;torsoDepth:number;shoulder:number;hip:number;patientMorph:{limb:number};pose:{elbowFlex:number;hipInternal:number;armRaise:number;shoulderRoll:number;kneeFlex:number};projectionId:string;placement:"standing"|"seated"|"upright-bucky"|"table";buckyTilt:number;opacity:number}){
 const Y={head:.955*H,neck:.86*H,shoulder:.79*H,chest:.70*H,pelvis:.47*H};
 const k=patientKinematics({H,s,shoulder,hip,limb:patientMorph.limb,elbowFlex:pose.elbowFlex,hipInternal:pose.hipInternal,armRaise:pose.armRaise,shoulderRoll:pose.shoulderRoll,kneeFlex:pose.kneeFlex,projectionId,placement,buckyTilt});
 const limb=.043*patientMorph.limb*s,ribHalf=torsoWidth*.72,ribDepth=Math.max(.06*s,torsoDepth*.42);
 const bones=useMemo(()=>{const out:BoneSpec[]=[];for(let i=0;i<24;i++){const y=Y.pelvis+.075*s+i*((Y.chest-.01*s)-(Y.pelvis+.075*s))/23;out.push(...vertebra(y,s,torsoDepth,i));if(i<23)out.push({a:[0,y-.012*s,.015*torsoDepth],b:[0,y+.012*s+.03*s,.015*torsoDepth],r:.004*s});}k.arms.forEach(a=>out.push({a:a.shoulder,b:a.upper,r:limb*1.08},{a:a.upper,b:a.elbow,r:limb*.82},{a:a.elbow,b:a.wrist,r:limb*.68},{a:a.wrist,b:a.hand,r:limb*.5}));k.legs.forEach(l=>out.push({a:l.hip,b:l.thigh,r:limb*1.2},{a:l.thigh,b:l.knee,r:limb*.94},{a:l.knee,b:l.calf,r:limb*.82},{a:l.calf,b:l.ankle,r:limb*.7},{a:l.ankle,b:l.foot,r:limb*.52}));return out;},[H,s,torsoDepth,k,limb,Y.chest,Y.pelvis]);
 const joints=useMemo(()=>[...k.arms.flatMap(a=>[{p:a.shoulder,r:limb*1.18},{p:a.elbow,r:limb*.92},{p:a.wrist,r:limb*.76}]),...k.legs.flatMap(l=>[{p:l.hip,r:limb*1.34},{p:l.knee,r:limb*1.08},{p:l.ankle,r:limb*.84}])],[k,limb]);
 const ribs=useMemo(()=>Array.from({length:12},(_,i)=>{const y=Y.chest+(11-i)*.018*s,width=ribHalf*(.99-i*.025),depth=ribDepth*(.98-i*.012);return Array.from({length:17},(_,j)=>{const t=j/16*Math.PI;return[Math.sin(t)*width,y-.012*s*Math.sin(t),Math.cos(t)*depth] as V3;});}),[Y.chest,s,ribHalf,ribDepth]);
 const sternum:V3=[0,Y.chest-.01*s,ribDepth*.86];
 return <group><group position={[0,Y.head,0]}><mesh scale={[.092*s,.108*s,.086*s]} renderOrder={10}><sphereGeometry args={[1,24,16]}/><meshPhysicalMaterial color="#e8e1cd" transparent opacity={opacity} roughness={.8} depthWrite={false} depthTest={false}/></mesh><mesh position={[0,-.052*s,.02*s]} scale={[.058*s,.047*s,.058*s]}><sphereGeometry args={[1,20,14]}/><meshPhysicalMaterial color="#e8e1cd" transparent opacity={opacity} roughness={.8} depthWrite={false} depthTest={false}/></mesh></group>
 {bones.map((b,i)=><Bone key={`bone-${i}`} a={b.a} b={b.b} radius={b.r} opacity={opacity}/>)}
 <FlatBone position={sternum} scale={[.014*s,.115*s,.018*s]} opacity={opacity}/>
 <FlatBone position={[-.72*k.shoulderWidth,Y.shoulder-.015*s,.075*torsoDepth]} scale={[.055*s,.085*s,.012*s]} rotation={[0,.15,-.18]} opacity={opacity*.92}/><FlatBone position={[.72*k.shoulderWidth,Y.shoulder-.015*s,.075*torsoDepth]} scale={[.055*s,.085*s,.012*s]} rotation={[0,-.15,.18]} opacity={opacity*.92}/>
 <FlatBone position={[-.30*k.shoulderWidth,Y.shoulder+.012*s,.012*s]} scale={[.075*s,.012*s,.009*s]} rotation={[0,0,-.08]} opacity={opacity}/><FlatBone position={[.30*k.shoulderWidth,Y.shoulder+.012*s,.012*s]} scale={[.075*s,.012*s,.009*s]} rotation={[0,0,.08]} opacity={opacity}/>
 {joints.map((j,i)=><Joint key={`joint-${i}`} position={j.p} radius={j.r} opacity={opacity}/>)}
 {ribs.map((points,i)=><group key={`rib-${i}`}>{points.slice(0,-1).map((p,j)=><Bone key={j} a={p} b={points[j+1]} radius={.0058*s} opacity={opacity*.9}/>)}</group>)}
 </group>;
}
