import { useEffect, useState } from "react";
import * as THREE from "three";
import { useSim } from "@/lib/sim/store";
import { patientById } from "@/lib/sim/patients";
import { patientKinematics, type V3 } from "@/lib/sim/patient-kinematics";
import type { PlacementMode } from "@/lib/sim/types";

interface AtlasPart { id:string; name:string; system:string; chunk:number; positions:number; normals:number; indices:number; vertexCount:number; indexCount:number; bounds:[number[],number[]]; }
interface AtlasManifest { version:string; parts:AtlasPart[]; chunks:{url:string;bytes:number}[]; triangles:number; }
const MODEL_ROOT="/models/human-atlas/";
const ATLAS_HEIGHT_M=1.7;
type BoneRegion="axial"|"scapula"|"clavicle"|"upperArm"|"forearm"|"hand"|"pelvis"|"thigh"|"lowerLeg"|"foot"|"rib";
function regionFor(name:string):BoneRegion{const n=name.toLowerCase();if(n.includes("rib")||n.includes("costal cartilage"))return"rib";if(n.includes("scapula"))return"scapula";if(n.includes("clavicle"))return"clavicle";if(n.includes("humerus"))return"upperArm";if(n.includes("radius")||n.includes("ulna"))return"forearm";if(n.includes("hand")||n.includes("metacarp")||n.includes("phalanx")||n.includes("carpal"))return"hand";if(n.includes("femur"))return"thigh";if(n.includes("tibia")||n.includes("fibula"))return"lowerLeg";if(n.includes("foot")||n.includes("metatars")||n.includes("talus")||n.includes("calcaneus")||n.includes("phalanges"))return"foot";if(n.includes("pelvis")||n.includes("ilium")||n.includes("ischium")||n.includes("pubis")||n.includes("sacrum"))return"pelvis";return"axial";}
function sideFor(bounds:[number[],number[]]):-1|1{return((bounds[0][0]+bounds[1][0])*.5)<0?-1:1;}

function createRibs(H:number,scale:number){const root=new THREE.Group();root.name="Bucky-Lab-natural-rib-cage";const material=new THREE.MeshStandardMaterial({color:"#ded8c4",roughness:.78,metalness:.02,transparent:true,opacity:.32,side:THREE.DoubleSide,depthWrite:true});const thoraxTop=.715*H,thoraxBottom=.475*H;for(let level=1;level<=12;level++){const t=(level-1)/11,y=thoraxTop-(thoraxTop-thoraxBottom)*t,width=(.205-.035*Math.abs(t-.35))*(level<=7?1:.92),posteriorZ=-.045+.012*t,anteriorZ=.075-.018*t,sternumX=.012*(1-t);const sidePoints=(side:-1|1):V3[]=>{const posterior:V3=[side*.018,y,posteriorZ],posterolateral:V3=[side*width*.46,y-.006,.005],lateral:V3=[side*width,y-.014,.030],anterolateral:V3=[side*width*.88,y-.022,anteriorZ*.72],anterior:V3=[side*width*.52,y-.030,anteriorZ];if(level<=7)return[posterior,posterolateral,lateral,anterolateral,anterior,[side*sternumX,y-.034,anteriorZ+.006]];if(level<=10)return[posterior,posterolateral,lateral,anterolateral,anterior];return[posterior,[side*width*.48,y-.006,.012],[side*width*.82,y-.018,.028],[side*width*.62,y-.028,anteriorZ*.82]];};([-1,1] as const).forEach(side=>{const curve=new THREE.CatmullRomCurve3(sidePoints(side).map(p=>new THREE.Vector3(...p)),false,"centripetal",.5);const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,28,.0042*scale,8,false),material);mesh.name=`Bucky Lab rib ${level}${side<0?" left":" right"}`;mesh.userData.atlasRegion="rib";root.add(mesh);});}return root;}

async function loadAtlas():Promise<THREE.Group>{const response=await fetch(`${MODEL_ROOT}atlas.json`,{cache:"force-cache"});if(!response.ok)throw new Error(`Human Atlas manifest failed to load (${response.status}).`);const atlas=await response.json() as AtlasManifest;const skeleton=atlas.parts.filter(p=>p.system==="skeletal"&&regionFor(p.name)!=="rib");if(!skeleton.length)throw new Error("Human Atlas contains no skeletal structures.");const root=new THREE.Group();root.name="BodyParts3D-Human-Atlas-Skeleton";const chunks=new Map<number,Array<{part:AtlasPart;buffer:ArrayBuffer}>>();await Promise.all([...new Set(skeleton.map(p=>p.chunk))].map(async chunkIndex=>{const chunk=atlas.chunks[chunkIndex];if(!chunk)throw new Error(`Human Atlas chunk ${chunkIndex} is missing.`);const r=await fetch(chunk.url,{cache:"force-cache"});if(!r.ok)throw new Error(`Human Atlas chunk ${chunkIndex} failed.`);const buffer=await r.arrayBuffer();if(buffer.byteLength!==chunk.bytes)throw new Error(`Human Atlas chunk ${chunkIndex} is incomplete.`);chunks.set(chunkIndex,skeleton.filter(p=>p.chunk===chunkIndex).map(part=>({part,buffer})));}));for(const {part,buffer} of [...chunks.values()].flat()){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.BufferAttribute(new Float32Array(buffer,part.positions,part.vertexCount*3),3));geometry.setAttribute("normal",new THREE.BufferAttribute(new Int16Array(buffer,part.normals,part.vertexCount*3),3,true));geometry.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,part.indices,part.indexCount),1));const region=regionFor(part.name),side=sideFor(part.bounds),center=new THREE.Vector3((part.bounds[0][0]+part.bounds[1][0])*.5,(part.bounds[0][1]+part.bounds[1][1])*.5,(part.bounds[0][2]+part.bounds[1][2])*.5);geometry.translate(-center.x,-center.y,-center.z);const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:"#ded8c4",roughness:.78,metalness:.02,transparent:true,opacity:.32,side:THREE.DoubleSide,depthWrite:true}));mesh.name=`Human Atlas bone ${part.name}`;mesh.userData.atlasRegion=region;mesh.userData.atlasSide=side;root.add(mesh);}root.add(createRibs(ATLAS_HEIGHT_M,1));return root;}

function articulate(root:THREE.Group,pose:ReturnType<typeof useSim.getState>["pose"],patient:ReturnType<typeof patientById>,placement:PlacementMode){const H=patient.heightCm/100,scale=H/ATLAS_HEIGHT_M,kin=patientKinematics({H,s:1,shoulder:patient.morph.shoulder,hip:patient.morph.hip,limb:patient.morph.limb,elbowFlex:pose.elbowFlex,hipInternal:pose.hipInternal,armRaise:pose.armRaise,armSide:pose.armSide,shoulderRoll:pose.shoulderRoll,armRotation:pose.armRotation,forearmRotation:pose.forearmRotation,kneeFlex:pose.kneeFlex,projectionId:"pa-chest",placement,buckyTilt:0});root.scale.setScalar(scale);const yAxis=new THREE.Vector3(0,1,0),midpoint=(a:THREE.Vector3,b:THREE.Vector3)=>a.clone().add(b).multiplyScalar(.5),local=(p:V3)=>new THREE.Vector3(p[0]/scale,p[1]/scale,p[2]/scale);root.children.forEach(object=>{if(!(object instanceof THREE.Mesh))return;const region=object.userData.atlasRegion as BoneRegion,side=object.userData.atlasSide as -1|1;object.rotation.set(0,0,0);if(region==="rib"||region==="axial")return;const arm=kin.arms[side<0?0:1],leg=kin.legs[side<0?0:1],shoulder=local(arm.shoulder),elbow=local(arm.elbow),wrist=local(arm.wrist),hand=local(arm.hand),hip=local(leg.hip),knee=local(leg.knee),ankle=local(leg.ankle),foot=local(leg.foot);const shoulderQ=new THREE.Quaternion().setFromUnitVectors(yAxis,new THREE.Vector3(...arm.elbow).sub(new THREE.Vector3(...arm.shoulder)).normalize()),forearmQ=new THREE.Quaternion().setFromUnitVectors(yAxis,new THREE.Vector3(...arm.wrist).sub(new THREE.Vector3(...arm.elbow)).normalize());if(region==="scapula"){object.position.copy(shoulder);return;}if(region==="clavicle"){object.position.copy(shoulder);return;}if(region==="upperArm"){object.position.copy(midpoint(shoulder,elbow));object.quaternion.copy(shoulderQ);return;}if(region==="forearm"){object.position.copy(midpoint(elbow,wrist));object.quaternion.copy(forearmQ);return;}if(region==="hand"){object.position.copy(hand);object.quaternion.copy(forearmQ);return;}if(region==="pelvis"){object.position.set(0,local([0,.47*H,0]).y,0);return;}const hipQ=new THREE.Quaternion().setFromUnitVectors(yAxis,new THREE.Vector3(...leg.knee).sub(new THREE.Vector3(...leg.hip)).normalize());if(region==="thigh"){object.position.copy(midpoint(hip,knee));object.quaternion.copy(hipQ);return;}const kneeQ=new THREE.Quaternion().setFromUnitVectors(yAxis,new THREE.Vector3(...leg.ankle).sub(new THREE.Vector3(...leg.knee)).normalize());if(region==="lowerLeg"){object.position.copy(midpoint(knee,ankle));object.quaternion.copy(kneeQ);return;}if(region==="foot"){object.position.copy(foot);object.quaternion.copy(kneeQ);return;}});}

export function HumanAtlasSkeletalOverlay(){const visibility=useSim(s=>s.anatomyVisibility.skeleton),pose=useSim(s=>s.pose),patientId=useSim(s=>s.patientId),placement=useSim(s=>s.equipment.placement),[root,setRoot]=useState<THREE.Group|null>(null),[,setError]=useState<string|null>(null);useEffect(()=>{if(!visibility||root)return;let cancelled=false;loadAtlas().then(group=>{if(cancelled){group.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});return;}setRoot(group);}).catch(err=>{if(!cancelled)setError(err instanceof Error?err.message:"Human Atlas failed to load");});return()=>{cancelled=true;};},[visibility,root]);useEffect(()=>{if(root&&visibility)articulate(root,pose,patientById(patientId),placement);},[root,visibility,pose,patientId,placement]);useEffect(()=>()=>{root?.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});},[root]);if(!visibility||!root)return null;return <primitive object={root}/>;}
