import { useEffect, useState } from "react";
import * as THREE from "three";
import { useSim } from "@/lib/sim/store";
import { patientById } from "@/lib/sim/patients";
import { patientKinematics } from "@/lib/sim/patient-kinematics";

interface AtlasPart { id:string; name:string; system:string; chunk:number; positions:number; normals:number; indices:number; vertexCount:number; indexCount:number; bounds?:[number[],number[]]; }
interface AtlasManifest { parts:AtlasPart[]; chunks:{url:string;bytes:number}[]; }
const MODEL_ROOT="/models/human-atlas/";
const ATLAS_HEIGHT_M=1.7;

const systemStyle=(system:string):{color:string;opacity:number}=>{const s=system.toLowerCase();if(s.includes("muscl"))return{color:"#9d5c55",opacity:.24};if(s.includes("fascia")||s.includes("connective")||s.includes("tendon")||s.includes("ligament"))return{color:"#c5a47a",opacity:.18};if(s.includes("cartilage")||s.includes("joint"))return{color:"#8bb9a5",opacity:.25};if(s.includes("vascular")||s.includes("arter")||s.includes("vein"))return{color:"#a84e59",opacity:.22};if(s.includes("nerv"))return{color:"#d4b35c",opacity:.18};if(s.includes("digest")||s.includes("organ")||s.includes("respir")||s.includes("urinar")||s.includes("reproduct"))return{color:"#9b6a62",opacity:.20};if(s.includes("adipos")||s.includes("fat"))return{color:"#c9a66a",opacity:.16};return{color:"#a87968",opacity:.14};};
function regionFor(name:string):"arm"|"leg"|"axial"{const n=name.toLowerCase();if(/humer|radius|ulna|carpal|metacarp|phalanx|upper arm|forearm|elbow|wrist|hand|shoulder|deltoid|biceps|triceps/.test(n))return"arm";if(/femur|tibia|fibula|patella|tarsal|metatars|phalanges|thigh|calf|knee|ankle|foot|glute/.test(n))return"leg";return"axial";}
function sideFor(bounds?:[number[],number[]]):-1|1{return bounds?(((bounds[0][0]+bounds[1][0])*.5)<0?-1:1):1;}
function smoothstep(a:number,b:number,x:number){const t=THREE.MathUtils.clamp((x-a)/(b-a),0,1);return t*t*(3-2*t);}
function rotatePoint(p:THREE.Vector3,pivot:THREE.Vector3,q:THREE.Quaternion){p.sub(pivot).applyQuaternion(q).add(pivot);}

async function loadAtlas():Promise<THREE.Group>{const r=await fetch(`${MODEL_ROOT}atlas.json`,{cache:"force-cache"});if(!r.ok)throw new Error(`Human Atlas manifest failed to load (${r.status}).`);const atlas=await r.json() as AtlasManifest;const parts=atlas.parts.filter(p=>p.system!=="integumentary"&&p.system!=="skeletal");const root=new THREE.Group();root.name="Bucky-Lab-Human-Atlas-All-Soft-Tissue";const byChunk=new Map<number,AtlasPart[]>();for(const part of parts){const list=byChunk.get(part.chunk)??[];list.push(part);byChunk.set(part.chunk,list);}await Promise.all([...byChunk.entries()].map(async([chunkIndex,chunkParts])=>{const chunk=atlas.chunks[chunkIndex];if(!chunk)throw new Error(`Human Atlas chunk ${chunkIndex} is missing.`);const cr=await fetch(chunk.url,{cache:"force-cache"});if(!cr.ok)throw new Error(`Human Atlas chunk ${chunkIndex} failed.`);const buffer=await cr.arrayBuffer();if(buffer.byteLength!==chunk.bytes)throw new Error(`Human Atlas chunk ${chunkIndex} is incomplete.`);for(const part of chunkParts){const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(new Float32Array(buffer,part.positions,part.vertexCount*3),3));g.setAttribute("normal",new THREE.BufferAttribute(new Int16Array(buffer,part.normals,part.vertexCount*3),3,true));g.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,part.indices,part.indexCount),1));const style=systemStyle(part.system);const mesh=new THREE.Mesh(g,new THREE.MeshPhysicalMaterial({color:style.color,roughness:.82,metalness:0,transparent:true,opacity:style.opacity,side:THREE.DoubleSide,depthWrite:false,depthTest:true}));mesh.name=`Human Atlas ${part.system} ${part.name}`;mesh.userData.atlasSystem=part.system;mesh.userData.atlasRegion=regionFor(part.name);mesh.userData.atlasSide=sideFor(part.bounds);mesh.userData.basePositions=new Float32Array(g.getAttribute("position").array as Float32Array);root.add(mesh);}}));return root;}

function articulate(root:THREE.Group,patient:ReturnType<typeof patientById>,pose:ReturnType<typeof useSim.getState>["pose"],placement:ReturnType<typeof useSim.getState>["equipment"]["placement"]){const H=patient.heightCm/100,scale=H/ATLAS_HEIGHT_M;const kin=patientKinematics({H,s:1,shoulder:patient.morph.shoulder,hip:patient.morph.hip,limb:patient.morph.limb,elbowFlex:pose.elbowFlex,hipInternal:pose.hipInternal,armRaise:pose.armRaise,armSide:pose.armSide,shoulderRoll:pose.shoulderRoll,armRotation:pose.armRotation,forearmRotation:pose.forearmRotation,kneeFlex:pose.kneeFlex,projectionId:"pa-chest",placement,buckyTilt:0});root.scale.setScalar(scale);const yAxis=new THREE.Vector3(0,1,0);root.traverse(object=>{if(!(object instanceof THREE.Mesh))return;const base=object.userData.basePositions as Float32Array|undefined;if(!base)return;const side=object.userData.atlasSide as -1|1,region=object.userData.atlasRegion as string;const arm=kin.arms[side<0?0:1],leg=kin.legs[side<0?0:1];const shoulder=new THREE.Vector3(...arm.shoulder),elbow=new THREE.Vector3(...arm.elbow),wrist=new THREE.Vector3(...arm.wrist),hip=new THREE.Vector3(...leg.hip),knee=new THREE.Vector3(...leg.knee),ankle=new THREE.Vector3(...leg.ankle);const shoulderQ=new THREE.Quaternion().setFromUnitVectors(yAxis,elbow.clone().sub(shoulder).normalize()),forearmQ=new THREE.Quaternion().setFromUnitVectors(yAxis,wrist.clone().sub(elbow).normalize()),hipQ=new THREE.Quaternion().setFromUnitVectors(yAxis,knee.clone().sub(hip).normalize()),kneeQ=new THREE.Quaternion().setFromUnitVectors(yAxis,ankle.clone().sub(knee).normalize());const attr=object.geometry.getAttribute("position"),target=attr.array as Float32Array;for(let i=0;i<target.length;i+=3){const original=new THREE.Vector3(base[i],base[i+1],base[i+2]),p=original.clone(),ax=Math.abs(p.x),py=p.y;if(region==="arm"){const upper=smoothstep(.14*scale,.23*scale,ax)*smoothstep(.55*H,.69*H,py)*(1-smoothstep(.69*H,.78*H,py)),fore=smoothstep(.22*scale,.34*scale,ax)*smoothstep(.40*H,.58*H,py)*(1-smoothstep(.57*H,.65*H,py));if(fore>.001){const ep=elbow.clone();rotatePoint(p,shoulder,shoulderQ);rotatePoint(ep,shoulder,shoulderQ);rotatePoint(p,ep,forearmQ);p.lerp(original,1-fore);}else if(upper>.001){rotatePoint(p,shoulder,shoulderQ);p.lerp(original,1-upper);}}else if(region==="leg"){const thigh=smoothstep(.10*scale,.20*scale,ax)*smoothstep(.31*H,.43*H,py)*(1-smoothstep(.45*H,.56*H,py)),lower=smoothstep(.10*scale,.20*scale,ax)*smoothstep(.05*H,.25*H,py)*(1-smoothstep(.22*H,.33*H,py));if(lower>.001){const kp=knee.clone();rotatePoint(p,hip,hipQ);rotatePoint(kp,hip,hipQ);rotatePoint(p,kp,kneeQ);p.lerp(original,1-lower);}else if(thigh>.001){rotatePoint(p,hip,hipQ);p.lerp(original,1-thigh);}}target[i]=p.x;target[i+1]=p.y;target[i+2]=p.z;}attr.needsUpdate=true;object.geometry.computeBoundingSphere();});}

export function HumanAtlasTissueOverlay(){const visible=useSim(s=>s.anatomyVisibility.muscle||s.anatomyVisibility.fat||s.anatomyVisibility.organs),patientId=useSim(s=>s.patientId),pose=useSim(s=>s.pose),placement=useSim(s=>s.equipment.placement),[root,setRoot]=useState<THREE.Group|null>(null);useEffect(()=>{let cancelled=false;loadAtlas().then(g=>{if(!cancelled)setRoot(g);}).catch(()=>{});return()=>{cancelled=true;};},[]);useEffect(()=>{if(root)articulate(root,patientById(patientId),pose,placement);},[root,patientId,pose,placement]);useEffect(()=>()=>{root?.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});},[root]);if(!visible||!root)return null;return <primitive object={root}/>;}
