import * as THREE from "three";
import { useMemo, type ReactNode } from "react";
import { useSim } from "@/lib/sim/store";
import { patientById } from "@/lib/sim/patients";
import { scaleLandmarkY, LANDMARKS } from "@/lib/sim/projections";
const SKIN_ROUGHNESS=0.58;type V3=[number,number,number];
function Skin({color,children}:{color:string;children?:ReactNode}){return <meshPhysicalMaterial color={color} roughness={SKIN_ROUGHNESS} metalness={0} clearcoat={0.035}>{children}</meshPhysicalMaterial>}
function Ellipsoid({position,scale,color,rotation=[0,0,0] as V3,castShadow=true}:{position:V3;scale:V3;color:string;rotation?:V3;castShadow?:boolean}){return <mesh position={position} rotation={rotation} scale={scale} castShadow={castShadow}><sphereGeometry args={[1,24,16]}/><Skin color={color}/></mesh>}
function Segment({a,b,radius,color}:{a:V3;b:V3;radius:number;color:string}){const s=new THREE.Vector3(...a),e=new THREE.Vector3(...b),d=e.clone().sub(s),len=d.length(),mid=s.clone().add(e).multiplyScalar(.5),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return <mesh position={mid} quaternion={q} castShadow><capsuleGeometry args={[radius,Math.max(.02,len-radius*1.55),8,16]}/><Skin color={color}/></mesh>}
function Hand({position,side,color,scale}:{position:V3;side:-1|1;color:string;scale:number}){return <group position={position}><Ellipsoid position={[0,0,0]} scale={[.055*scale,.085*scale,.035*scale]} color={color}/>{[0,1,2,3].map(i=><Segment key={i} a={[(-.035+i*.022)*scale,-.01*scale,0]} b={[(-.035+i*.022)*scale+side*.004*scale,-.075*scale,0]} radius=.009*scale color={color}/>)}<Segment a={[side*.045*scale,.01*scale,0]} b={[side*.075*scale,-.045*scale,0]} radius=.011*scale color={color}/></group>}
function Foot({position,color,scale}:{position:V3;color:string;scale:number}){return <group position={position}><Ellipsoid position={[0,0,0]} scale={[.065*scale,.045*scale,.145*scale]} color={color}/><Ellipsoid position={[0,-.006,.115*scale]} scale={[.062*scale,.04*scale,.075*scale]} color={color}/>{[0,1,2,3,4].map(i=><Ellipsoid key={i} position={[(i-2)*.018*scale,.006,.18*scale]} scale={[.013*scale,.018*scale,.025*scale]} color={color}/>)}</group>}
function Head({skin,hair,chin,scale}:{skin:string;hair:string;chin:number;scale:number}){return <group rotation={[-chin,0,0]} scale={scale}><Ellipsoid position={[0,.92,0]} scale={[.095,.12,.09]} color={skin}/><Ellipsoid position={[0,.865,.015]} scale={[.065,.055,.072]} color={skin}/><Ellipsoid position={[0,.855,.075]} scale={[.025,.018,.028]} color={skin}/><Ellipsoid position={[-.052,.938,.079]} scale={[.012,.009,.006]} color="#24303a"/><Ellipsoid position={[.052,.938,.079]} scale={[.012,.009,.006]} color="#24303a"/><Ellipsoid position={[0,.916,.088]} scale={[.012,.025,.012]} color={skin}/><Ellipsoid position={[0,.878,.09]} scale={[.025,.008,.006]} color="#9d6262"/><Ellipsoid position={[-.103,.925,0]} scale={[.012,.028,.022]} color={skin}/><Ellipsoid position={[.103,.925,0]} scale={[.012,.028,.022]} color={skin}/><Ellipsoid position={[0,1.015,-.005]} scale={[.101,.07,.088]} color={hair} castShadow={false}/><Ellipsoid position={[0,.986,.07]} scale={[.085,.04,.045]} color={hair} castShadow={false}/></group>}
export function PatientModel(){
 const patientId=useSim(s=>s.patientId),pose=useSim(s=>s.pose),equipment=useSim(s=>s.equipment),showLandmarks=useSim(s=>s.showLandmarks),setLandmarkCR=useSim(s=>s.setLandmarkCR),projectionId=useSim(s=>s.projectionId);const patient=patientById(patientId),m=patient.morph,h=patient.heightCm/100,skin=patient.skin;const bodyWidth=.16*m.torsoWidth,chestDepth=.12*m.torsoDepth,shoulderWidth=.205*m.shoulder,limb=.043*m.limb,scale=h/1.7;const yaw=pose.rotationY*Math.PI/180,oblique=pose.oblique*Math.PI/180,kyphosis=m.kyphosis*.22;const wall=equipment.placement==='upright-bucky'||equipment.placement==='standing'||equipment.placement==='seated',tableTop=equipment.tableHeight+.075,bodyThickness=Math.max(.13,chestDepth*1.05);let groupPos:V3,groupRot:V3;if(wall){const standY=equipment.placement==='seated'?.38:.01;groupPos=[equipment.patientX,standY+equipment.patientY,(equipment.placement==='upright-bucky'?- .48:-.32)+equipment.patientZ];groupRot=[0,yaw,0]}else{groupPos=[equipment.tableX+equipment.patientX,tableTop+bodyThickness+equipment.patientY,equipment.tableZ+h*.5+equipment.patientZ];groupRot=[-Math.PI/2,0,yaw]}
 const Y={head:.94,neck:.86,shoulder:.81,chest:.73,waist:.63,pelvis:.52,knee:.25,ankle:.055};const hipGap=.085*m.hip,elbow=(pose.elbowFlex*Math.PI)/180,hipInt=pose.hipInternal*Math.PI/180;const lateralChest=projectionId==='lat-chest',paChest=projectionId==='pa-chest',raise=Math.max(0,Math.min(1,pose.armRaise));const landmarks=LANDMARKS.filter(l=>l.y>0&&!['3rd-mcp','midcarpal','elbow','patella-apex','medial-epicondyle-knee','malleoli','3rd-mt'].includes(l.id));const bodyGeometry=useMemo(()=>({pelvis:[.13*m.hip,.105*m.abdomen,.12*m.torsoDepth] as V3,abdomen:[.155*m.torsoWidth,.16*m.abdomen,.11*m.torsoDepth] as V3,chest:[bodyWidth,.22*m.torsoLength,chestDepth] as V3}),[bodyWidth,chestDepth,m.abdomen,m.hip,m.torsoDepth,m.torsoLength,m.torsoWidth]);
 return <group position={groupPos} rotation={groupRot}><group rotation={[kyphosis,oblique,0]}><Ellipsoid position={[0,Y.pelvis,0]} scale={bodyGeometry.pelvis} color={skin}/><Ellipsoid position={[0,Y.waist,0]} scale={bodyGeometry.abdomen} color={skin}/><Ellipsoid position={[0,Y.chest,0]} scale={bodyGeometry.chest} color={skin}/>{patient.sex==='female'&&<><Ellipsoid position={[-.065*m.torsoWidth,Y.chest+.015,chestDepth*.68]} scale={[.075*m.breast,.09*m.breast,.045*m.breast]} color={skin}/><Ellipsoid position={[.065*m.torsoWidth,Y.chest+.015,chestDepth*.68]} scale={[.075*m.breast,.09*m.breast,.045*m.breast]} color={skin}/></>}<Ellipsoid position={[0,.70,0]} scale={[bodyGeometry.chest[0]*1.035,bodyGeometry.chest[1]*.42,bodyGeometry.chest[2]*1.035]} color={patient.gown} castShadow={false}/><Ellipsoid position={[0,Y.neck,0]} scale={[.055*m.shoulder,.075,.06]} color={skin}/><Head skin={skin} hair={patient.hair} chin={pose.chinUp*.16} scale={scale}/>
 {([-1,1] as const).map(side=>{const shoulder:V3=[side*shoulderWidth,Y.shoulder,0];let upper:V3,elbowPoint:V3,wrist:V3;if(lateralChest&&raise>.35){upper=[side*(shoulderWidth+.03),Y.shoulder+.12*raise,.02];elbowPoint=[side*(shoulderWidth+.015),Y.shoulder+.22*raise,.035];wrist=[side*.075,Y.shoulder+.31*raise,.04]}else if(paChest&&pose.shoulderRoll>.55){upper=[side*(shoulderWidth+.02),Y.shoulder-.045,0];elbowPoint=[side*(shoulderWidth+.015),Y.shoulder-.12,.055];wrist=[side*(bodyWidth*.52),Y.waist+.02,.07]}else{upper=[side*(shoulderWidth+.055*m.limb),Y.shoulder+.08*raise,0];elbowPoint=[upper[0]+side*.005,upper[1]-.16*Math.cos(elbow),.02*Math.sin(elbow)];wrist=[elbowPoint[0]+side*.012,elbowPoint[1]-.16*Math.cos(elbow),.04*Math.sin(elbow)]}return <group key={side}><Ellipsoid position={shoulder} scale={[.065*m.shoulder,.065,.065]} color={skin}/><Segment a={shoulder} b={upper} radius={limb*1.28} color={skin}/><Ellipsoid position={elbowPoint} scale={[limb*1.28,limb*1.18,limb*1.2]} color={skin}/><Segment a={upper} b={elbowPoint} radius={limb} color={skin}/><Segment a={elbowPoint} b={wrist} radius={limb*.86} color={skin}/><Hand position={wrist} side={side} color={skin} scale={m.limb}/></group>})}
 {([-1,1] as const).map(side=>{const hip:V3=[side*hipGap,Y.pelvis-.01,0],thigh:V3=[side*(hipGap+.008),Y.knee+.12,side*.008*Math.sin(hipInt)],knee:V3=[side*(hipGap+.006),Y.knee,side*.012*Math.sin(hipInt)],calf:V3=[side*(hipGap+.006),Y.ankle+.12,side*.008],ankle:V3=[side*(hipGap+.006),Y.ankle,side*.01];return <group key={side}><Ellipsoid position={hip} scale={[limb*1.75,limb*1.8,limb*1.7]} color={skin}/><Segment a={hip} b={thigh} radius={limb*1.45} color={skin}/><Ellipsoid position={knee} scale={[limb*1.38,limb*1.28,limb*1.35]} color={skin}/><Segment a={thigh} b={knee} radius={limb*1.12} color={skin}/><Segment a={knee} b={calf} radius={limb*.94} color={skin}/><Ellipsoid position={ankle} scale={[limb*.8,limb*.72,limb*.82]} color={skin}/><Foot position={[ankle[0],ankle[1]-.012,ankle[2]+.025]} color={skin} scale={m.limb}/></group>})}</group>{showLandmarks&&landmarks.map(lm=>{const yy=h-(scaleLandmarkY(lm.y,patient.heightCm)/patient.heightCm)*h,xx=(lm.x/100)*m.torsoWidth;return <mesh key={lm.id} position={[xx,yy,bodyThickness+.01]} onClick={e=>{e.stopPropagation();setLandmarkCR(scaleLandmarkY(lm.y,patient.heightCm),lm.x*m.torsoWidth)}}><sphereGeometry args={[.012,10,8]}/><meshBasicMaterial color="#e2c35a"/></mesh>})}</group>;
}