import type { Patient, Projection, ExposureState, TubeState, ExposureMetrics } from "./types";
import { primaryTransmission, relativeTubeOutput } from "./nist-attenuation";

export function incidentFluence(kvp:number,mas:number,sidCm:number,grid:boolean){const output=relativeTubeOutput(kvp),dist=Math.pow(100/Math.max(60,sidCm),2),gridFactor=grid?.34:1;return mas*output*dist*gridFactor*42;}
export function partThickness(patient:Patient,projection:Projection){if(!projection)throw new Error("Radiography projection is missing");switch(projection.anatomy){case"torso-ap":case"torso-lat":if(projection.region==="Thorax")return patient.thickness.chest;if(projection.region==="Abdomen")return patient.thickness.abdomen;if(projection.region==="Pelvis & hips")return patient.thickness.pelvis;if(projection.id.includes("lumbar"))return patient.thickness.lumbar;if(projection.id.includes("cspine")||projection.id.includes("c-spine"))return patient.thickness.cspine;return patient.thickness.abdomen;case"cspine-lat":return patient.thickness.cspine;case"skull-lat":return patient.thickness.skull;case"shoulder-ap":return patient.thickness.shoulder;case"knee-ap":case"knee-lat":return patient.thickness.knee;default:return patient.thickness.extremity;}}
export function suggestedTechnique(patient:Patient,projection:Projection){const refT=projection.region==="Thorax"?22:projection.region==="Abdomen"||projection.region==="Pelvis & hips"?22:projection.anatomy.includes("hand")||projection.anatomy.includes("wrist")||projection.anatomy.includes("foot")?4:12,t=partThickness(patient,projection),cm=t-refT;let{kvp,mas}=projection;if(Math.abs(cm)>=8){kvp=Math.round(kvp*(cm>0?1.15:.87));mas*=Math.pow(2,(cm>0?cm-4:cm+4)/4);}else mas*=Math.pow(2,cm/4);if(projection.anatomy==="torso-lat"||projection.anatomy==="cspine-lat")mas*=1.05;return{kvp:Math.min(125,Math.max(40,Math.round(kvp))),mas:Math.min(200,Math.max(.5,Math.round(mas*10)/10))};}
export function fieldScatter(collimW:number,collimH:number,thickness:number,grid:boolean){const scatter=(collimW*collimH/900)*(thickness/22)*.22;return grid?scatter*.18:scatter;}
export function exposureIndex(meanSignal:number){return 100*Math.log10(Math.max(1e-6,meanSignal)*12);}
export function classifyEI(ei:number):ExposureMetrics["eiStatus"]{return ei<170?"under":ei>340?"over":"optimal";}
export function representativeTransmission(patient:Patient,projection:Projection,kvp:number){const t=partThickness(patient,projection),isChest=projection.region==="Thorax";return isChest?primaryTransmission({soft:t*.34,inflatedLung:t*.46,trabecularBone:t*.055,adipose:t*.145},kvp):primaryTransmission({soft:t*.76,trabecularBone:t*.11,adipose:t*.13},kvp);}
export function superimpositionIndex(patient:Patient,projection:Projection){const t=partThickness(patient,projection),thicknessBurden=Math.min(1,t/35),projectionBurden=projection.anatomy==="torso-lat"?.78:projection.anatomy==="torso-ap"?.58:projection.anatomy==="skull-lat"||projection.anatomy==="cspine-lat"?.72:.30;return Math.min(1,projectionBurden*.68+thicknessBurden*.32);}
export function predictEI(patient:Patient,projection:Projection,exposure:ExposureState,tube:TubeState){const T=representativeTransmission(patient,projection,exposure.kvp),I0=incidentFluence(exposure.kvp,exposure.mas,tube.sid,exposure.grid&&projection.setup!=="tabletop"),t=partThickness(patient,projection),scatter=fieldScatter(tube.collimationW,tube.collimationH,t,exposure.grid);return exposureIndex(I0*T+I0*scatter*.15);}

type MetricsArgs={meanSignal:number;noise:number;contrast:number;saturation?:number;patient:Patient;projection:Projection;exposure:ExposureState;tube:TubeState;scatterFrac?:number};
export function buildMetrics(meanSignal:number,noise:number,contrast:number,saturation:number,patient:Patient,projection:Projection,exposure:ExposureState,tube:TubeState):ExposureMetrics;
export function buildMetrics(args:MetricsArgs):ExposureMetrics;
export function buildMetrics(a:number|MetricsArgs,noise=0,contrast=0,saturation=0,patient?:Patient,projection?:Projection,exposure?:ExposureState,tube?:TubeState):ExposureMetrics{
 if(typeof a==="object"){({meanSignal:a,noise,contrast,saturation=0,patient,projection,exposure,tube}=a);}
 if(!patient||!projection||!exposure||!tube)throw new Error("Exposure metrics require patient, projection, exposure and tube state");
 const meanSignal=typeof a==="number"?a:(a as unknown as number),ei=exposureIndex(meanSignal),t=partThickness(patient,projection),I0=incidentFluence(exposure.kvp,exposure.mas,tube.sid,exposure.grid),fieldAreaCm2=(tube.collimationW/10)*(tube.collimationH/10),patientSizeFactor=Math.max(.72,Math.min(1.55,1+(t-20)/60)),receptorAttenuation=exposure.grid?1.28:1,kVFactor=Math.pow(exposure.kvp/75,.35),distanceFactor=Math.pow(100/Math.max(60,tube.sid),2),entranceDose=I0*.012*distanceFactor*patientSizeFactor*receptorAttenuation/Math.max(.7,kVFactor),dap=entranceDose*fieldAreaCm2,transmission=representativeTransmission(patient,projection,exposure.kvp),scatter=fieldScatter(tube.collimationW,tube.collimationH,t,exposure.grid),scatterFraction=Math.min(1,scatter/Math.max(1e-6,transmission+scatter)),attenuationIndex=Math.min(1,-Math.log(Math.max(1e-6,transmission))/5),superimposition=superimpositionIndex(patient,projection);
 return{ei,eiStatus:classifyEI(ei),noise,contrast,saturation,dap,entranceDose,predictedEI:predictEI(patient,projection,exposure,tube),transmission,scatterFraction,attenuationIndex,superimpositionIndex:superimposition};
}
