import type { Patient } from "./types";

export const PATIENTS: Patient[] = [
  {
    id: "elise",
    name: "Elise V.",
    age: 26,
    sex: "female",
    habitus: "asthenic",
    heightCm: 176,
    weightKg: 52,
    skin: "#e0b496",
    hair: "#1c1410",
    gown: "#c9d4dc",
    thickness: {
      chest: 16,
      abdomen: 14,
      pelvis: 16,
      cspine: 10,
      lumbar: 18,
      skull: 15,
      extremity: 3,
      shoulder: 10,
      knee: 10,
    },
    morph: {
      torsoWidth: 0.78,
      torsoDepth: 0.72,
      torsoLength: 1.12,
      limb: 0.82,
      shoulder: 0.84,
      hip: 0.88,
      abdomen: 0.7,
      kyphosis: 0.05,
      breast: 0.45,
    },
    notes: "Long thorax, low viscera, thin soft-tissue envelope. Easy to clip lung bases if you centre on a sthenic T7.",
  },
  {
    id: "malik",
    name: "Malik R.",
    age: 31,
    sex: "male",
    habitus: "hyposthenic",
    heightCm: 183,
    weightKg: 74,
    skin: "#6b3e2e",
    hair: "#140c08",
    gown: "#c9d4dc",
    thickness: {
      chest: 20,
      abdomen: 18,
      pelvis: 20,
      cspine: 12,
      lumbar: 22,
      skull: 16,
      extremity: 4,
      shoulder: 12,
      knee: 11,
    },
    morph: {
      torsoWidth: 0.9,
      torsoDepth: 0.88,
      torsoLength: 1.06,
      limb: 0.92,
      shoulder: 0.95,
      hip: 0.9,
      abdomen: 0.85,
      kyphosis: 0,
      breast: 0,
    },
    notes: "Lean, slightly long-chested. Close to many handbook diagrams — a fair first model.",
  },
  {
    id: "amara",
    name: "Amara S.",
    age: 34,
    sex: "female",
    habitus: "sthenic",
    heightCm: 168,
    weightKg: 68,
    skin: "#c99578",
    hair: "#3a2418",
    gown: "#c9d4dc",
    thickness: {
      chest: 22,
      abdomen: 20,
      pelvis: 22,
      cspine: 12,
      lumbar: 24,
      skull: 16,
      extremity: 4,
      shoulder: 13,
      knee: 12,
    },
    morph: {
      torsoWidth: 1,
      torsoDepth: 0.98,
      torsoLength: 1,
      limb: 1,
      shoulder: 0.96,
      hip: 1.08,
      abdomen: 1,
      kyphosis: 0,
      breast: 1,
    },
    notes: "Average adult female. Handbook kVp/mAs values are charted against this build unless noted.",
  },
  {
    id: "tomas",
    name: "Tomas H.",
    age: 41,
    sex: "male",
    habitus: "sthenic",
    heightCm: 178,
    weightKg: 82,
    skin: "#c4a07a",
    hair: "#5c4630",
    gown: "#c9d4dc",
    thickness: {
      chest: 24,
      abdomen: 22,
      pelvis: 24,
      cspine: 13,
      lumbar: 26,
      skull: 17,
      extremity: 5,
      shoulder: 14,
      knee: 13,
    },
    morph: {
      torsoWidth: 1.08,
      torsoDepth: 1.05,
      torsoLength: 1,
      limb: 1.08,
      shoulder: 1.12,
      hip: 1.02,
      abdomen: 1.05,
      kyphosis: 0.02,
      breast: 0,
    },
    notes: "Average adult male. Expect a stop or two more mAs than Amara on trunk work.",
  },
  {
    id: "gordon",
    name: "Gordon P.",
    age: 58,
    sex: "male",
    habitus: "hypersthenic",
    heightCm: 174,
    weightKg: 124,
    skin: "#a56b4a",
    hair: "#9a9aa0",
    gown: "#c9d4dc",
    thickness: {
      chest: 32,
      abdomen: 34,
      pelvis: 36,
      cspine: 16,
      lumbar: 36,
      skull: 18,
      extremity: 6,
      shoulder: 18,
      knee: 16,
    },
    morph: {
      torsoWidth: 1.38,
      torsoDepth: 1.42,
      torsoLength: 0.88,
      limb: 1.28,
      shoulder: 1.3,
      hip: 1.32,
      abdomen: 1.55,
      kyphosis: 0.08,
      breast: 0.15,
    },
    notes: "Broad, high diaphragm, short thorax. Needs a grid, more mAs, and a higher centring point on the chest. Scatter will destroy contrast if you open the shutters.",
  },
  {
    id: "ruth",
    name: "Ruth L.",
    age: 79,
    sex: "female",
    habitus: "asthenic",
    heightCm: 156,
    weightKg: 46,
    skin: "#d4b08c",
    hair: "#c8c4bc",
    gown: "#c9d4dc",
    thickness: {
      chest: 17,
      abdomen: 15,
      pelvis: 17,
      cspine: 10,
      lumbar: 18,
      skull: 15,
      extremity: 3,
      shoulder: 10,
      knee: 9,
    },
    morph: {
      torsoWidth: 0.82,
      torsoDepth: 0.78,
      torsoLength: 0.92,
      limb: 0.78,
      shoulder: 0.8,
      hip: 0.9,
      abdomen: 0.75,
      kyphosis: 0.45,
      breast: 0.35,
    },
    notes: "Elderly asthenic with thoracic kyphosis. Watch C7/T1 on the lateral cervical and do not clip the apices on PA chest.",
  },
];

export function patientById(id: string): Patient {
  return PATIENTS.find((p) => p.id === id) ?? PATIENTS[2]!;
}
