import type { Landmark, Projection } from "./types";

/** Anatomical surface landmarks, cm from vertex on a 170 cm sthenic model. */
export const LANDMARKS: Landmark[] = [
  { id: "vertex", label: "Vertex", y: 2, x: 0 },
  { id: "nasion", label: "Nasion", y: 10, x: 0 },
  { id: "eam", label: "EAM", y: 13, x: 8 },
  { id: "c4", label: "Thyroid cartilage (C4)", y: 18, x: 0 },
  { id: "c7", label: "Vertebra prominens (C7)", y: 22, x: 0 },
  { id: "sternal-notch", label: "Sternal notch (T2/3)", y: 26, x: 0 },
  { id: "t7", label: "Inferior angle of scapula (T7)", y: 40, x: 0 },
  { id: "xiphisternum", label: "Xiphisternum (T10)", y: 48, x: 0 },
  { id: "lower-costal", label: "Lower costal margin (L3)", y: 58, x: 0 },
  { id: "iliac-crest", label: "Iliac crest (L4)", y: 66, x: 16 },
  { id: "asis", label: "ASIS", y: 72, x: 12 },
  { id: "symphysis", label: "Symphysis pubis", y: 84, x: 0 },
  { id: "greater-trochanter", label: "Greater trochanter", y: 86, x: 14 },
  { id: "femoral-head", label: "Femoral head", y: 82, x: 8 },
  { id: "coracoid", label: "Coracoid process", y: 28, x: 16 },
  { id: "3rd-mcp", label: "3rd MCP joint", y: 0, x: 0 },
  { id: "midcarpal", label: "Midcarpal joint", y: 0, x: 0 },
  { id: "elbow", label: "Mid-elbow joint", y: 0, x: 0 },
  { id: "patella-apex", label: "1 cm distal to patellar apex", y: 0, x: 0 },
  { id: "medial-epicondyle-knee", label: "2.5 cm distal to medial epicondyle", y: 0, x: 0 },
  { id: "malleoli", label: "Midway between malleoli", y: 0, x: 0 },
  { id: "3rd-mt", label: "Base of 3rd metatarsal", y: 0, x: 0 },
];

export const PROJECTIONS: Projection[] = [
  {
    id: "pa-chest",
    name: "PA chest (erect)",
    shortName: "PA chest",
    region: "Thorax",
    anatomy: "torso-ap",
    setup: "wall",
    recumbency: "erect",
    irW: 35,
    irH: 43,
    grid: true,
    sidCm: 180,
    tubeAngle: 0,
    kvp: 125,
    mas: 2.5,
    collimationW: 33,
    collimationH: 41,
    cr: { x: 0, y: 40 },
    landmarkId: "t7",
    centring: "Horizontal beam to T7 — inferior angle of the scapula, MSP.",
    position:
      "Erect, facing the IR. Chin raised, shoulders rolled forward with the backs of the hands on the hips so the scapulae clear the lungs. MSP perpendicular to the IR.",
    beam: "Horizontal central ray, FFD 180 cm, centred to the spinous process of T7.",
    collimation: "Lung fields: 4 cm above the shoulders to include the apices, below both costophrenic angles, skin margins laterally.",
    criteria: [
      "Both lungs from apices to costophrenic angles",
      "Scapulae clear of the lung fields",
      "Sternal ends of clavicles equidistant from the spine",
      "Trachea and carina visible; ten posterior ribs above the diaphragm",
    ],
    include: ["apices", "costophrenic angles", "both lungs"],
    respiration: "inspiration",
  },
  {
    id: "lat-chest",
    name: "Left lateral chest (erect)",
    shortName: "Lat. chest",
    region: "Thorax",
    anatomy: "torso-lat",
    setup: "wall",
    recumbency: "erect",
    laterality: "left",
    irW: 35,
    irH: 43,
    grid: true,
    sidCm: 180,
    tubeAngle: 0,
    kvp: 125,
    mas: 8,
    collimationW: 33,
    collimationH: 41,
    cr: { x: 0, y: 40 },
    landmarkId: "t7",
    centring: "Horizontal beam to T7 in the mid-coronal plane.",
    position:
      "Erect, left side against the IR, arms elevated and crossed on the head. MSP parallel to the IR.",
    beam: "Horizontal central ray, FFD 180 cm, to T7 mid-coronal (about 5 cm anterior to the spinous process).",
    collimation: "Posterior ribs to the sternum, apices to costophrenic angles.",
    criteria: [
      "From apices to both costophrenic angles",
      "Posterior ribs superimposed (no rotation)",
      "Arms clear of the lung apices",
      "Sternum and thoracic spine included",
    ],
    include: ["apices", "costophrenic angles", "sternum"],
    respiration: "inspiration",
  },
  {
    id: "ap-abdomen",
    name: "AP abdomen supine (KUB)",
    shortName: "AP abdomen",
    region: "Abdomen",
    anatomy: "torso-ap",
    setup: "table",
    recumbency: "supine",
    irW: 35,
    irH: 43,
    grid: true,
    sidCm: 110,
    tubeAngle: 0,
    kvp: 73,
    mas: 25,
    collimationW: 33,
    collimationH: 41,
    cr: { x: 0, y: 66 },
    landmarkId: "iliac-crest",
    centring: "Vertical beam to the midline at the level of the iliac crests.",
    position: "Supine, MSP to the table midline, arms abducted. Legs extended.",
    beam: "Vertical central ray, FFD 110 cm, midline at iliac crest (L4).",
    collimation: "Diaphragm if possible, to the pubic rami, lateral skin margins.",
    criteria: [
      "Pubic rami included",
      "Psoas outlines and properitoneal fat lines visible when exposure is correct",
      "No rotation — spinous processes midline, iliac wings symmetric",
      "Bowel gas pattern and renal outlines where possible",
    ],
    include: ["iliac crests", "pubic rami", "psoas"],
    respiration: "expiration",
  },
  {
    id: "ap-pelvis",
    name: "AP pelvis",
    shortName: "AP pelvis",
    region: "Pelvis & hips",
    anatomy: "torso-ap",
    setup: "table",
    recumbency: "supine",
    irW: 35,
    irH: 43,
    grid: true,
    sidCm: 110,
    tubeAngle: 0,
    kvp: 73,
    mas: 25,
    collimationW: 41,
    collimationH: 33,
    cr: { x: 0, y: 78 },
    landmarkId: "symphysis",
    centring: "Midline, midway between the ASIS and the superior border of the pubic symphysis.",
    position:
      "Supine, MSP midline. Both feet internally rotated 15–20° to bring the femoral necks parallel to the IR.",
    beam: "Vertical central ray, FFD 110 cm, to a point in the midline 5 cm below the ASIS (midway ASIS–symphysis).",
    collimation: "Iliac crests to proximal femoral shafts, both hips.",
    criteria: [
      "Iliac crests to lesser trochanters",
      "Femoral necks without foreshortening (lesser trochanters barely seen)",
      "Symmetric obturator foramina and iliac wings",
      "Sacrum and pubic rami included",
    ],
    include: ["iliac crests", "both hips", "proximal femora"],
  },
  {
    id: "ap-hip",
    name: "AP unilateral hip",
    shortName: "AP hip",
    region: "Pelvis & hips",
    anatomy: "torso-ap",
    setup: "table",
    recumbency: "supine",
    laterality: "left",
    irW: 24,
    irH: 30,
    grid: true,
    sidCm: 110,
    tubeAngle: 0,
    kvp: 73,
    mas: 20,
    collimationW: 22,
    collimationH: 28,
    cr: { x: 8, y: 82 },
    landmarkId: "femoral-head",
    centring:
      "To the femoral head — 2.5 cm distal to the midpoint of a line from ASIS to the pubic symphysis.",
    position: "Supine, affected limb internally rotated 15–20° unless contraindicated (NOF fracture).",
    beam: "Vertical central ray, FFD 110 cm, over the femoral head.",
    collimation: "Whole of the femoral head and neck, acetabulum, proximal third of the femur.",
    criteria: [
      "Acetabulum, femoral head, neck and proximal shaft",
      "Greater trochanter in profile; lesser trochanter superimposed",
      "Joint space visible",
    ],
    include: ["acetabulum", "femoral neck", "greater trochanter"],
  },
  {
    id: "lat-cspine",
    name: "Lateral cervical spine (erect)",
    shortName: "Lat. C-spine",
    region: "Spine",
    anatomy: "cspine-lat",
    setup: "wall",
    recumbency: "erect",
    laterality: "left",
    irW: 24,
    irH: 30,
    grid: false,
    sidCm: 180,
    tubeAngle: 0,
    kvp: 70,
    mas: 12.5,
    collimationW: 16,
    collimationH: 26,
    cr: { x: 0, y: 18 },
    landmarkId: "c4",
    centring:
      "Horizontal ray centred to C4 (thyroid cartilage), vertically below the mastoid process.",
    position:
      "Erect, left shoulder against the IR. Shoulders depressed, chin slightly raised so the mandible clears C1–C2. MSP parallel to the IR.",
    beam: "Horizontal central ray, FFD 180 cm, to C4.",
    collimation: "Base of skull to T1, skin of the neck. Tight laterally.",
    criteria: [
      "C1 to the top of T1 (C7/T1 junction)",
      "Bodies, facet joints and spinous processes in profile",
      "Mandible clear of C1–C2",
      "Soft-tissue neck and air column of the pharynx/trachea",
    ],
    include: ["C1", "C7/T1", "prevertebral soft tissue"],
  },
  {
    id: "ap-cspine",
    name: "AP cervical spine C3–C7",
    shortName: "AP C-spine",
    region: "Spine",
    anatomy: "torso-ap",
    setup: "wall",
    recumbency: "erect",
    irW: 18,
    irH: 24,
    grid: false,
    sidCm: 110,
    tubeAngle: 15,
    kvp: 70,
    mas: 12.5,
    collimationW: 16,
    collimationH: 26,
    cr: { x: 0, y: 18 },
    landmarkId: "c4",
    centring: "15° cephalad central ray to C4.",
    position: "Erect, MSP perpendicular to the IR, chin raised enough to clear the mandible from C3–C4.",
    beam: "15° cephalad central ray to C4.",
    collimation: "C3–C7 with the lateral soft tissues included.",
    criteria: ["C3–C7 vertebral bodies", "Intervertebral disc spaces", "Spinous processes approximately midline"],
    include: ["C3", "C7", "disc spaces"],
  },
];

export function projectionById(id:string): Projection {
  return PROJECTIONS.find(p => p.id === id) ?? PROJECTIONS[0];
}
