import type { Landmark, Projection } from "./types";

/** Anatomical surface landmarks, cm from vertex on a 170 cm sthenic model. */
export const LANDMARKS: Landmark[] = [
  { id: "vertex", label: "Vertex", y: 2, x: 0 }, { id: "nasion", label: "Nasion", y: 10, x: 0 }, { id: "eam", label: "EAM", y: 13, x: 8 },
  { id: "c4", label: "Thyroid cartilage (C4)", y: 18, x: 0 }, { id: "c7", label: "Vertebra prominens (C7)", y: 22, x: 0 },
  { id: "sternal-notch", label: "Sternal notch (T2/3)", y: 26, x: 0 }, { id: "t7", label: "Inferior angle of scapula (T7)", y: 40, x: 0 },
  { id: "xiphisternum", label: "Xiphisternum (T10)", y: 48, x: 0 }, { id: "lower-costal", label: "Lower costal margin (L3)", y: 58, x: 0 },
  { id: "iliac-crest", label: "Iliac crest (L4)", y: 66, x: 16 }, { id: "asis", label: "ASIS", y: 72, x: 12 },
  { id: "symphysis", label: "Symphysis pubis", y: 84, x: 0 }, { id: "greater-trochanter", label: "Greater trochanter", y: 86, x: 14 },
  { id: "femoral-head", label: "Femoral head", y: 82, x: 8 }, { id: "coracoid", label: "Coracoid process", y: 28, x: 16 },
  { id: "3rd-mcp", label: "3rd MCP joint", y: 0, x: 0 }, { id: "midcarpal", label: "Midcarpal joint", y: 0, x: 0 },
  { id: "elbow", label: "Mid-elbow joint", y: 0, x: 0 }, { id: "patella-apex", label: "1 cm distal to patellar apex", y: 0, x: 0 },
  { id: "medial-epicondyle-knee", label: "2.5 cm distal to medial epicondyle", y: 0, x: 0 }, { id: "malleoli", label: "Midway between malleoli", y: 0, x: 0 },
  { id: "3rd-mt", label: "Base of 3rd metatarsal", y: 0, x: 0 },
  { id: "whole-body-centre", label: "Whole-body centre", y: 85, x: 0 },
];

export const PROJECTIONS: Projection[] = [
  { id:"ap-full-body", name:"AP whole-body benchmark", shortName:"Whole body", region:"Whole body", anatomy:"full-body-ap", setup:"wall", recumbency:"erect", irW:60, irH:180, grid:true, sidCm:200, tubeAngle:0, kvp:90, mas:12, collimationW:60, collimationH:180, cr:{x:0,y:85}, landmarkId:"whole-body-centre", centring:"Horizontal beam to the body midline at approximately the level of the upper pelvis for a complete head-to-foot survey.", position:"Erect AP benchmark position with the MSP perpendicular to the detector, head neutral, arms by the sides and lower limbs extended symmetrically.", beam:"Horizontal central ray, SID 200 cm, centred to the whole-body detector midpoint.", collimation:"Vertex to feet with both lateral soft-tissue margins and both upper limbs included.", criteria:["Entire skeleton from skull to feet included","Both upper and lower limbs included without clipping","Soft-tissue body contour continuous from head to feet","Thoracic, abdominal and pelvic soft tissues distinguishable","No gross rotation or limb asymmetry"], include:["skull","thorax","abdomen","pelvis","upper limbs","lower limbs","feet"] },
  { id:"pa-chest", name:"PA chest (erect)", shortName:"PA chest", region:"Thorax", anatomy:"torso-ap", setup:"wall", recumbency:"erect", irW:35, irH:43, grid:true, sidCm:180, tubeAngle:0, kvp:125, mas:2.5, collimationW:33, collimationH:41, cr:{x:0,y:40}, landmarkId:"t7", centring:"Horizontal beam to T7 — inferior angle of the scapula, MSP.", position:"Erect, facing the IR. Chin raised, shoulders rolled forward with the backs of the hands on the hips so the scapulae clear the lungs. MSP perpendicular to the IR.", beam:"Horizontal central ray, FFD 180 cm, centred to the spinous process of T7.", collimation:"Lung fields: 4 cm above the shoulders to include the apices, below both costophrenic angles, skin margins laterally.", criteria:["Both lungs from apices to costophrenic angles","Scapulae clear of the lung fields","Sternal ends of clavicles equidistant from the spine","Trachea and carina visible; ten posterior ribs above the diaphragm"], include:["apices","costophrenic angles","both lungs"], respiration:"inspiration" },
  { id:"lat-chest", name:"Left lateral chest (erect)", shortName:"Lat. chest", region:"Thorax", anatomy:"torso-lat", setup:"wall", recumbency:"erect", laterality:"left", irW:35, irH:43, grid:true, sidCm:180, tubeAngle:0, kvp:125, mas:8, collimationW:33, collimationH:41, cr:{x:0,y:40}, landmarkId:"t7", centring:"Horizontal beam to T7 in the mid-coronal plane.", position:"Erect, left side against the IR, arms elevated and crossed on the head. MSP parallel to the IR.", beam:"Horizontal central ray, FFD 180 cm, to T7 mid-coronal (about 5 cm anterior to the spinous process).", collimation:"Posterior ribs to the sternum, apices to costophrenic angles.", criteria:["From apices to both costophrenic angles","Posterior ribs superimposed (no rotation)","Arms clear of the lung apices","Sternum and thoracic spine included"], include:["apices","costophrenic angles","sternum"], respiration:"inspiration" },
  { id:"ap-abdomen", name:"AP abdomen supine (KUB)", shortName:"AP abdomen", region:"Abdomen", anatomy:"torso-ap", setup:"table", recumbency:"supine", irW:35, irH:43, grid:true, sidCm:110, tubeAngle:0, kvp:73, mas:25, collimationW:33, collimationH:41, cr:{x:0,y:66}, landmarkId:"iliac-crest", centring:"Vertical beam to the midline at the level of the iliac crests.", position:"Supine, MSP to the table midline, arms abducted. Legs extended.", beam:"Vertical central ray, FFD 110 cm, midline at iliac crest (L4).", collimation:"Diaphragm if possible, to the pubic rami, lateral skin margins.", criteria:["Pubic rami included","Psoas outlines and properitoneal fat lines visible when exposure is correct","No rotation — spinous processes midline, iliac wings symmetric","Bowel gas pattern and renal outlines where possible"], include:["iliac crests","pubic rami","psoas"], respiration:"expiration" },
  { id:"ap-pelvis", name:"AP pelvis", shortName:"AP pelvis", region:"Pelvis & hips", anatomy:"torso-ap", setup:"table", recumbency:"supine", irW:35, irH:43, grid:true, sidCm:110, tubeAngle:0, kvp:73, mas:25, collimationW:41, collimationH:33, cr:{x:0,y:78}, landmarkId:"symphysis", centring:"Midline, midway between the ASIS and the superior border of the pubic symphysis.", position:"Supine, MSP midline. Both feet internally rotated 15–20° to bring the femoral necks parallel to the IR.", beam:"Vertical central ray, FFD 110 cm, to a point in the midline 5 cm below the ASIS (midway ASIS–symphysis).", collimation:"Iliac crests to proximal femoral shafts, both hips.", criteria:["Iliac crests to lesser trochanters","Femoral necks without foreshortening (lesser trochanters barely seen)","Symmetric obturator foramina and iliac wings","Sacrum and pubic rami included"], include:["iliac crests","both hips","proximal femora"] },
  { id:"ap-hip", name:"AP unilateral hip", shortName:"AP hip", region:"Pelvis & hips", anatomy:"torso-ap", setup:"table", recumbency:"supine", laterality:"left", irW:24, irH:30, grid:true, sidCm:110, tubeAngle:0, kvp:73, mas:20, collimationW:22, collimationH:28, cr:{x:8,y:82}, landmarkId:"femoral-head", centring:"To the femoral head — 2.5 cm distal to the midpoint of a line from ASIS to the pubic symphysis.", position:"Supine, affected limb internally rotated 15–20° unless contraindicated (NOF fracture).", beam:"Vertical central ray, FFD 110 cm, over the femoral head.", collimation:"Whole of the femoral head and neck, acetabulum, proximal third of the femur.", criteria:["Acetabulum, femoral head, neck and proximal shaft","Greater trochanter in profile; lesser trochanter superimposed","Joint space visible"], include:["acetabulum","femoral neck","greater trochanter"] },
  { id:"lat-cspine", name:"Lateral cervical spine (erect)", shortName:"Lat. C-spine", region:"Spine", anatomy:"cspine-lat", setup:"wall", recumbency:"erect", laterality:"left", irW:24, irH:30, grid:false, sidCm:180, tubeAngle:0, kvp:70, mas:12.5, collimationW:16, collimationH:26, cr:{x:0,y:18}, landmarkId:"c4", centring:"Horizontal ray centred to C4 (thyroid cartilage), vertically below the mastoid process.", position:"Erect, left shoulder against the IR. Shoulders depressed, chin slightly raised so the mandible clears C1–C2. MSP parallel to the IR.", beam:"Horizontal central ray, FFD 180 cm, to C4.", collimation:"Base of skull to T1, skin of the neck. Tight laterally.", criteria:["C1 to the top of T1 (C7/T1 junction)","Bodies, facet joints and spinous processes in profile","Mandible clear of C1–C2","Soft-tissue neck and air column of the pharynx/trachea"], include:["C1","C7/T1","prevertebral soft tissue"] },
  { id:"ap-cspine", name:"AP cervical spine C3–C7", shortName:"AP C-spine", region:"Spine", anatomy:"torso-ap", setup:"wall", recumbency:"erect", irW:18, irH:24, grid:false, sidCm:110, tubeAngle:15, kvp:63, mas:6.3, collimationW:14, collimationH:20, cr:{x:0,y:18}, landmarkId:"c4", centring:"15° cranial, to the thyroid cartilage (C4), so the mandible clears the mid-cervical bodies.", position:"Erect or supine, MSP perpendicular. Chin raised until the occlusal plane is perpendicular to the IR.", beam:"15° cranial angulation, FFD 110 cm, centred to C4.", collimation:"C3 to C7, lateral skin of the neck.", criteria:["C3–C7 vertebral bodies and uncinate processes","Spinous processes in the midline","Mandible superimposed over the occiput, not the mid-cervical bodies"], include:["C3","C7","transverse processes"] },
  { id:"ap-lumbar", name:"AP lumbar spine", shortName:"AP lumbar", region:"Spine", anatomy:"torso-ap", setup:"table", recumbency:"supine", irW:24, irH:35, grid:true, sidCm:110, tubeAngle:0, kvp:73, mas:32, collimationW:16, collimationH:32, cr:{x:0,y:58}, landmarkId:"lower-costal", centring:"Midline at the lower costal margin (L3).", position:"Supine, hips and knees slightly flexed to flatten the lumbar lordosis. MSP midline.", beam:"Vertical central ray, FFD 110 cm, to L3 in the midline.", collimation:"T12 to the sacral base, sacroiliac joints. Tight laterally to the psoas.", criteria:["T12 to the sacrum","Spinous processes midline; pedicles symmetric","Sacroiliac joints included","Psoas margins visible with a correct exposure"], include:["T12","sacral base","SI joints"], respiration:"expiration" },
  { id:"lat-lumbar", name:"Lateral lumbar spine", shortName:"Lat. lumbar", region:"Spine", anatomy:"torso-lat", setup:"table", recumbency:"supine", laterality:"left", irW:24, irH:35, grid:true, sidCm:150, tubeAngle:0, kvp:90, mas:40, collimationW:18, collimationH:32, cr:{x:0,y:58}, landmarkId:"lower-costal", centring:"Lower costal margin in the mid-axillary line (L3).", position:"True lateral (left side against the IR). Hips and knees flexed. Arms forward. Pads to keep the long axis of the spine parallel to the table.", beam:"Vertical (or horizontal if erect) central ray to L3 mid-axillary, FFD 150 cm.", collimation:"T12 to the sacral promontory, anterior vertebral bodies to the spinous processes.", criteria:["T12 to the sacrum","Bodies in profile with open disc spaces","Posterior elements superimposed (no rotation)","Intervertebral foramina visible"], include:["T12","sacrum","vertebral bodies"], respiration:"expiration" },
  { id:"pa-hand", name:"PA hand", shortName:"PA hand", region:"Upper limb", anatomy:"hand-pa", setup:"tabletop", recumbency:"supine", irW:18, irH:24, grid:false, sidCm:110, tubeAngle:0, kvp:52, mas:2, collimationW:12, collimationH:22, cr:{x:0,y:0}, landmarkId:"3rd-mcp", centring:"Head of the third metacarpal.", position:"Seated, palmar aspect of the hand on the IR, fingers slightly separated, forearm in the same plane. Shoulder, elbow and wrist aligned.", beam:"Vertical central ray, FFD 110 cm, to the head of the 3rd metacarpal.", collimation:"Skin margins, fingertips to distal radius and ulna.", criteria:["Fingertips to distal radius/ulna","Equal concavity of the metacarpal shafts (no rotation)","Open MCP and IP joints","Soft-tissue outlines and trabecular bone"], include:["fingertips","distal radius","carpals"] },
  { id:"pa-wrist", name:"PA wrist", shortName:"PA wrist", region:"Upper limb", anatomy:"wrist-pa", setup:"tabletop", recumbency:"supine", irW:18, irH:24, grid:false, sidCm:110, tubeAngle:0, kvp:55, mas:2, collimationW:10, collimationH:14, cr:{x:0,y:0}, landmarkId:"midcarpal", centring:"Midcarpal joint.", position:"Seated, palm down, fingers slightly flexed to bring the carpus in contact with the IR. Forearm in the same plane.", beam:"Vertical central ray, FFD 110 cm, to the midcarpal joint.", collimation:"Proximal metacarpals to distal radius and ulna, skin margins.", criteria:["Proximal metacarpals, carpals, distal radius and ulna","Ulnar styloid in profile; no rotation of the radius","Joint spaces through the carpus"], include:["carpals","distal radius","proximal metacarpals"] },
  { id:"ap-elbow", name:"AP elbow", shortName:"AP elbow", region:"Upper limb", anatomy:"elbow-ap", setup:"tabletop", recumbency:"supine", irW:18, irH:24, grid:false, sidCm:110, tubeAngle:0, kvp:57, mas:3, collimationW:12, collimationH:16, cr:{x:0,y:0}, landmarkId:"elbow", centring:"Mid-elbow joint, 2.5 cm distal to the epicondyles.", position:"Seated, arm fully extended, posterior aspect of the elbow on the IR. Epicondyles equidistant from the IR.", beam:"Vertical central ray, FFD 110 cm, through the elbow joint.", collimation:"Distal third of the humerus to the proximal third of the radius/ulna.", criteria:["Elbow joint space open","Epicondyles in profile (no rotation)","Radial head, neck and tuberosity slightly superimposed on the ulna"], include:["distal humerus","elbow joint","proximal radius/ulna"] },
  { id:"ap-shoulder", name:"AP shoulder (external rotation)", shortName:"AP shoulder", region:"Upper limb", anatomy:"shoulder-ap", setup:"table", recumbency:"supine", laterality:"left", irW:24, irH:30, grid:false, sidCm:110, tubeAngle:0, kvp:60, mas:4, collimationW:22, collimationH:22, cr:{x:16,y:30}, landmarkId:"coracoid", centring:"2.5 cm inferior to the coracoid process.", position:"Erect or supine, posterior aspect of the shoulder against the IR. Arm slightly abducted, external rotation so the epicondyles are parallel to the IR (palm forward).", beam:"Vertical or horizontal central ray, FFD 110 cm, 2.5 cm inferior to the coracoid.", collimation:"Whole of the clavicle, scapula and proximal humerus.", criteria:["Glenohumeral joint, acromion, coracoid, proximal humerus","Greater tubercle in profile laterally","Glenoid not overly overlapped by the humeral head"], include:["glenohumeral joint","clavicle","proximal humerus"] },
  { id:"ap-knee", name:"AP knee", shortName:"AP knee", region:"Lower limb", anatomy:"knee-ap", setup:"tabletop", recumbency:"supine", irW:18, irH:24, grid:false, sidCm:110, tubeAngle:5, kvp:63, mas:4, collimationW:14, collimationH:20, cr:{x:0,y:0}, landmarkId:"patella-apex", centring:"1 cm distal to the apex of the patella, 5° cranial if the pelvis is large.", position:"Supine or seated, leg extended, epicondyles parallel to the IR.", beam:"5° cranial (optional), FFD 110 cm, 1 cm distal to the patellar apex.", collimation:"Distal third of the femur to the proximal third of the tibia/fibula.", criteria:["Knee joint space open and symmetric","Patella superimposed on the distal femur","Fibular head slightly overlapped by the tibia (no rotation)"], include:["distal femur","knee joint","proximal tibia"] },
  { id:"lat-knee", name:"Lateral knee", shortName:"Lat. knee", region:"Lower limb", anatomy:"knee-lat", setup:"tabletop", recumbency:"supine", laterality:"left", irW:18, irH:24, grid:false, sidCm:110, tubeAngle:5, kvp:63, mas:4, collimationW:14, collimationH:20, cr:{x:0,y:0}, landmarkId:"medial-epicondyle-knee", centring:"2.5 cm distal to the medial femoral epicondyle, 5–7° cranial.", position:"Patient turned onto the affected side, knee flexed 20–30°. Femoral epicondyles superimposed, patella perpendicular to the IR.", beam:"5–7° cranial, FFD 110 cm, to a point 2.5 cm distal to the medial epicondyle.", collimation:"Distal femur, knee joint, proximal tibia/fibula, patella in profile.", criteria:["Femoral condyles superimposed","Patellofemoral joint open","Knee flexed 20–30°","Proximal tibiofibular joint slightly open"], include:["patella","femoral condyles","proximal tibia"] },
  { id:"dp-foot", name:"Dorsoplantar foot", shortName:"DP foot", region:"Lower limb", anatomy:"foot-dp", setup:"tabletop", recumbency:"supine", irW:18, irH:24, grid:false, sidCm:110, tubeAngle:10, kvp:57, mas:2, collimationW:12, collimationH:22, cr:{x:0,y:0}, landmarkId:"3rd-mt", centring:"Base of the third metatarsal, 10° toward the heel.", position:"Seated, plantar aspect of the foot on the IR, knee flexed. Leg vertical.", beam:"10° cranial (toward the heel), FFD 110 cm, to the base of the 3rd metatarsal.", collimation:"Toes to the calcaneum, skin margins.", criteria:["Whole foot including calcaneum and toes","Equal spacing of the metatarsals (no rotation)","Open TMT joints where the angle is correct"], include:["toes","metatarsals","calcaneum"] },
  { id:"ap-ankle", name:"AP ankle", shortName:"AP ankle", region:"Lower limb", anatomy:"ankle-ap", setup:"tabletop", recumbency:"supine", irW:18, irH:24, grid:false, sidCm:110, tubeAngle:0, kvp:60, mas:3, collimationW:12, collimationH:16, cr:{x:0,y:0}, landmarkId:"malleoli", centring:"Midway between the malleoli.", position:"Supine or seated, leg extended, posterior aspect of the ankle on the IR. Malleoli equidistant (foot dorsiflexed).", beam:"Vertical central ray, FFD 110 cm, midway between the malleoli.", collimation:"Distal third of the tibia/fibula to the proximal talus, skin margins.", criteria:["Mortise of the ankle joint","Malleoli in profile","Talar dome in the joint space"], include:["malleoli","talar dome","distal tibia"] },
  { id:"lat-skull", name:"Lateral skull", shortName:"Lat. skull", region:"Skull", anatomy:"skull-lat", setup:"table", recumbency:"supine", laterality:"left", irW:24, irH:30, grid:true, sidCm:110, tubeAngle:0, kvp:66, mas:16, collimationW:22, collimationH:26, cr:{x:0,y:10}, landmarkId:"eam", centring:"A point 5 cm superior to the EAM (midway between glabella and the external occipital protuberance).", position:"True lateral. MSP parallel to the IR, interpupillary line perpendicular, IOML parallel to the long axis of the IR.", beam:"Perpendicular central ray, FFD 110 cm, 5 cm above the EAM.", collimation:"Skin of the vertex, frontal, occipital and mandibular outlines.", criteria:["Whole of the cranium and mandible","Orbital roofs, EAMs and greater wings of sphenoid superimposed","Sella turcica in profile","Air in the sinuses and nasopharynx"], include:["vertex","sella","mandible"] },
];

export const REGIONS: Projection["region"][] = ["Whole body","Thorax","Abdomen","Pelvis & hips","Spine","Upper limb","Lower limb","Skull"];

export function projectionById(id: string): Projection { return PROJECTIONS.find(p => p.id === id) ?? PROJECTIONS[0]!; }
export function scaleLandmarkY(y: number, heightCm: number): number { return (y / 170) * heightCm; }
