import type { Patient, Projection, SimPose, TubeState, ExposureState, RadiographResult } from "./types";
import { sampleAnatomy, hashPatient, type Paths, type SampleCtx } from "./anatomy";
import { addSharedOrganPaths } from "./shared-anatomy-sampling";
import { addSharedTissueLayers } from "./shared-tissue-sampling";
import { buildMetrics, fieldScatter, incidentFluence, muEffective, partThickness } from "./exposure";
import { clamp, fbm } from "./geometry";
import { projectionGeometry } from "./projection-physics";
import { scoreExposure } from "./scoring";
import { caseById } from "./case-bank";
import type { PathologyId } from "./requests";

const PHOTO_CACHE = new Map<string, ImageData>();
const PHOTO_WAIT = new Map<string, Promise<ImageData | null>>();
function loadPhoto(src: string): Promise<ImageData | null> { if (PHOTO_CACHE.has(src)) return Promise.resolve(PHOTO_CACHE.get(src)!); const pending = PHOTO_WAIT.get(src); if (pending) return pending; const p = new Promise<ImageData | null>((resolve) => { const img = new Image(); img.crossOrigin = "anonymous"; img.onload = () => { const c = document.createElement("canvas"); c.width = img.naturalWidth; c.height = img.naturalHeight; const g = c.getContext("2d"); if (!g) { resolve(null); return; } g.drawImage(img, 0, 0); const data = g.getImageData(0, 0, c.width, c.height); PHOTO_CACHE.set(src, data); resolve(data); }; img.onerror = () => resolve(null); img.src = src; }); PHOTO_WAIT.set(src, p); return p; }
export function preloadRadiographAssets(projections: Projection[]) { for (const pr of projections) if (pr.referenceImage) void loadPhoto(pr.referenceImage); }
function pathsToOD(p: Paths, kvp: number): number { return muEffective("air", kvp) * p.air + muEffective("lung", kvp) * p.lung + muEffective("fat", kvp) * p.fat + muEffective("soft", kvp) * p.soft * 1.05 + muEffective("bone", kvp) * p.bone * 1.15 + muEffective("cortical", kvp) * p.cortical * 1.35 + muEffective("air", kvp) * p.gas * 40 + muEffective("metal", kvp) * p.metal; }
function samplePhoto(photo: ImageData, u: number, v: number): number | null { if (u < 0 || v < 0 || u > 1 || v > 1) return null; const x = u * (photo.width - 1), y = v * (photo.height - 1), x0 = Math.floor(x), y0 = Math.floor(y), x1 = Math.min(photo.width - 1, x0 + 1), y1 = Math.min(photo.height - 1, y0 + 1), fx = x - x0, fy = y - y0; const idx = (xx: number, yy: number) => (yy * photo.width + xx) * 4; const g00 = photo.data[idx(x0, y0)]! / 255, g10 = photo.data[idx(x1, y0)]! / 255, g01 = photo.data[idx(x0, y1)]! / 255, g11 = photo.data[idx(x1, y1)]! / 255; return g00 * (1 - fx) * (1 - fy) + g10 * fx * (1 - fy) + g01 * (1 - fx) * fy + g11 * fx * fy; }
function invDisplay(g: number): number { const x = clamp(g, 0, 1); return Math.pow(1.001 - x, 2.1) * 0.15 + Math.pow(x, 2.4) * 0.02 + 0.004; }
function localCoords(projection: Projection, patient: Patient, pose: SimPose, px: number, py: number, w: number, h: number, tube: TubeState, geometry: ReturnType<typeof projectionGeometry>): { x: number; y: number } { const cmX = ((px + 0.5) / w - 0.5) * tube.collimationW / geometry.magnification, cmY = ((py + 0.5) / h - 0.5) * tube.collimationH / geometry.magnification, angle = (tube.angle * Math.PI) / 180, angleShift = Math.tan(angle) * geometry.oidCm, rotation = (pose.rotationY * Math.PI) / 180, oblique = (pose.oblique * Math.PI) / 180, rx = cmX * Math.cos(rotation) + cmY * Math.sin(rotation) * 0.12, ry = cmY * Math.cos(oblique) - cmX * Math.sin(oblique) * 0.18 - angleShift; if (projection.anatomy === "torso-ap" || projection.anatomy === "torso-lat" || projection.anatomy === "cspine-lat" || projection.anatomy === "shoulder-ap") return { x: tube.crX + rx, y: tube.crY + ry }; if (projection.anatomy === "skull-lat") return { x: rx, y: ry + (tube.crY - 10) * 0.4 }; return { x: rx + tube.crX * 0.15, y: ry + (tube.crY - projection.cr.y) * 0.25 }; }
function photoUV(projection: Projection, x: number, y: number, patient: Patient): { u: number; v: number } | null { if (!projection.referenceImage) return null; if (projection.id === "pa-chest") { const y0 = 12 * (patient.heightCm / 170), y1 = 62 * (patient.heightCm / 170), hw = 20 * patient.morph.torsoWidth; return { u: (x + hw) / (hw * 2), v: (y - y0) / (y1 - y0) }; } if (projection.id === "pa-hand") return { u: (x + 6) / 12, v: (8 - y) / 18 }; return null; }
function ellipse(x: number, y: number, cx: number, cy: number, rx: number, ry: number): number { const q = ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2; return q < 1 ? 1 - q : 0; }
function pathologyDelta(pathologyId: PathologyId, x: number, y: number, projection: Projection): number {
  if (projection.anatomy !== "torso-ap" && projection.anatomy !== "torso-lat") return 0;
  if (pathologyId === "consolidation") return 0.7 * ellipse(x, y, -5.5, 51, 6.5, 7.5);
  if (pathologyId === "pneumothorax") return -0.75 * ellipse(x, y, -8.5, 19, 6.5, 8.5);
  if (pathologyId === "rib-fracture") return 0.22 * ellipse(x, y, 10, 34, 1.2, 1.1);
  return 0;
}
function addPacemaker(paths: Paths, x: number, y: number, projection: Projection, enabled: boolean) {
  if (!enabled || (projection.anatomy !== "torso-ap" && projection.anatomy !== "torso-lat")) return;
  const generator = ellipse(x, y, -8, 29, 2.7, 3.4);
  const lead1 = Math.exp(-(((x + 3.5) ** 2) / 1.4 + ((y - 35) ** 2) / 34));
  const lead2 = Math.exp(-(((x + 4.5) ** 2) / 1.2 + ((y - 40) ** 2) / 38));
  paths.metal += (generator + lead1 + lead2) * 14;
}
export async function renderRadiograph(args: { patient: Patient; projection: Projection; pose: SimPose; tube: TubeState; exposure: ExposureState; pathologyId?: PathologyId; caseId?: string | null; width?: number; height?: number; }): Promise<RadiographResult> {
  const { patient, projection, pose, tube, exposure, pathologyId = "none", caseId } = args; const simCase = caseById(caseId); const aspect = tube.collimationW / tube.collimationH, height = args.height ?? 768, width = args.width ?? Math.round(height * aspect); const photo = projection.referenceImage ? await loadPhoto(projection.referenceImage) : null; const kvp = exposure.kvp, grid = exposure.grid, geometry = projectionGeometry(projection, tube, pose, exposure.focalSpot), I0 = incidentFluence(kvp, exposure.mas, tube.sid, grid); const thickness = partThickness(patient, projection), scatterFrac = fieldScatter(tube.collimationW, tube.collimationH, thickness, grid), seed = hashPatient(patient.id), ctx: SampleCtx = { patient, projection, pose, seed }; const signal = new Float32Array(width * height); let sum = 0;
  for (let py = 0; py < height; py++) for (let px = 0; px < width; px++) { const { x, y } = localCoords(projection, patient, pose, px, py, width, height, tube, geometry); const paths = sampleAnatomy(x, y, ctx); if (projection.anatomy === "torso-ap" || projection.anatomy === "torso-lat") { addSharedTissueLayers(paths, x, y, patient, pose); addSharedOrganPaths(paths, x, y, patient, pose); addPacemaker(paths, x, y, projection, simCase?.device === "pacemaker"); } let od = pathsToOD(paths, kvp) * (0.55 + thickness / 40); od = Math.max(0.01, od + pathologyDelta(pathologyId, x, y, projection)); let T = Math.exp(-od); if (photo) { const uv = photoUV(projection, x, y, patient); if (uv) { const g = samplePhoto(photo, uv.u, uv.v); if (g !== null) { const edge = Math.min(uv.u, uv.v, 1 - uv.u, 1 - uv.v) * 8, fade = clamp(edge, 0, 1), Tphoto = clamp(invDisplay(g) / 0.12, 0.002, 1), habitus = Math.exp(-muEffective("soft", kvp) * (thickness - 22) * 0.35); T = T * (1 - fade) + Tphoto * habitus * fade; } } } const boneMask = paths.bone > 0.3 || paths.cortical > 0.15 ? 1 : 0, trabFine = (fbm(x * 3.2, y * 3.2, seed) - 0.5) * 0.12, trabCoarse = (fbm(x * 1.1, y * 1.1, seed + 3) - 0.5) * 0.07, cortEdge = paths.cortical > 0.4 ? (fbm(x * 6, y * 6, seed + 7) - 0.5) * 0.05 : 0, softVar = (fbm(x * 0.6, y * 0.6, seed + 11) - 0.5) * 0.04 * (paths.soft > 1 ? 1 : 0); const trabecula = 1 + boneMask * (trabFine + trabCoarse + cortEdge) + softVar, scat = I0 * scatterFrac * (0.5 + 0.5 * (paths.soft + paths.lung > 0 ? 1 : 0.15)); let sig = I0 * T * trabecula + scat; if (paths.air > 20 && paths.soft < 0.2 && paths.bone < 0.2) sig = I0 * 1.05 + scat * 0.2; signal[py * width + px] = sig; sum += sig; }
  const n = width * height, mean = sum / n, well = 280, canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height; const g = canvas.getContext("2d")!, img = g.createImageData(width, height); let sat = 0, noiseAcc = 0, contrastAcc = 0, contrastN = 0; const logMean = Math.log(mean + 1e-5), contrastScale = clamp((kvp - 45) / 80, 0, 1), windowW = 1.55 + contrastScale * 2.4, windowL = logMean + (mean > 100 ? 0.2 : mean < 10 ? -0.35 : 0), noiseGain = 0.35 + 1.8 / Math.sqrt(Math.max(0.25, mean / 40)), blurRadius = clamp(Math.round(geometry.geometricUnsharpnessMm * 1.7), 0, 4), blurWeight = blurRadius > 0 ? Math.min(0.42, geometry.geometricUnsharpnessMm * 0.16) : 0;
  for (let i = 0; i < n; i++) { let sig = signal[i]!; const nx = i % width, ny = (i / width) | 0; if (blurRadius > 0 && nx > 0 && nx < width - 1) { let neighbour = 0, count = 0; for (let dx = 1; dx <= blurRadius; dx++) { const falloff = 1 / (dx + 1); neighbour += (signal[i - dx]! + signal[i + dx]!) * falloff; count += 2 * falloff; } if (count > 0) sig = sig * (1 - blurWeight) + (neighbour / count) * blurWeight; } const sigma = noiseGain / Math.sqrt(Math.max(0.35, sig)), nse = (fbm(nx * 0.85, ny * 0.85, seed + 4) - 0.5) * 2 * sigma * 10; sig = Math.max(0, sig + nse); noiseAcc += Math.abs(nse); if (sig > well) { sig = well; sat += 1; } const L = Math.log(sig + 1e-5); let d = 1 - clamp((L - windowL) / windowW + 0.5, 0, 1); if (kvp >= 100) d = 0.08 + d * 0.84; else if (kvp <= 55) { d = d < 0.5 ? d * 0.85 : 0.5 + (d - 0.5) * 1.15; d = clamp(d, 0, 1); } let tone = clamp(d, 0, 1); tone = tone * tone * (3 - 2 * tone); const v = Math.round(clamp(tone, 0, 1) * 255), o = i * 4; img.data[o] = v; img.data[o + 1] = v; img.data[o + 2] = v; img.data[o + 3] = 255; if (nx > 0) { contrastAcc += Math.abs(v - img.data[(i - 1) * 4]!); contrastN++; } }
  const markerLetter = exposure.marker === "L" || exposure.marker === "R" ? exposure.marker : "R"; stampMarker(img, width, height, markerLetter, Math.round(width * 0.08), Math.round(height * 0.12)); drawCrosshair(img, width, height, width / 2, height / 2); g.putImageData(img, 0, 0); const dataUrl = canvas.toDataURL("image/png"); const metrics = buildMetrics(mean, noiseAcc / n, contrastN ? contrastAcc / contrastN / 255 : 0, sat / n, patient, projection, exposure, tube); const scores = scoreExposure({ patient, projection, pose, tube, exposure, metrics }); const overall = scores.reduce((a, c) => a + c.weight * gradeNum(c.grade), 0) / scores.reduce((a, c) => a + c.weight, 0), overallGrade = overall >= 0.85 ? "excellent" : overall >= 0.62 ? "acceptable" : "repeat"; return { metrics, scores, overall, overallGrade, width, height, dataUrl }; }
function gradeNum(g: "excellent" | "acceptable" | "repeat"): number { return g === "excellent" ? 1 : g === "acceptable" ? 0.7 : 0.25; }
function stampMarker(img: ImageData, w: number, h: number, letter: "L" | "R", x: number, y: number) { const glyph = letter === "L" ? L_GLYPH : R_GLYPH, scale = 5; const put = (px: number, py: number, r: number, gg: number, b: number) => { if (px < 0 || py < 0 || px >= w || py >= h) return; const o = (py * w + px) * 4; img.data[o] = r; img.data[o + 1] = gg; img.data[o + 2] = b; img.data[o + 3] = 255; }; for (let gy = 0; gy < glyph.length; gy++) { const row = glyph[gy]!; for (let gx = 0; gx < row.length; gx++) if (row[gx] === "#") { for (let oy = -1; oy <= scale; oy++) for (let ox = -1; ox <= scale; ox++) put(x + gx * scale + ox, y + gy * scale + oy, 10, 10, 12); for (let oy = 0; oy < scale; oy++) for (let ox = 0; ox < scale; ox++) put(x + gx * scale + ox, y + gy * scale + oy, 250, 250, 255); } } }
const L_GLYPH = ["#    ", "#    ", "#    ", "#    ", "#####"], R_GLYPH = ["#### ", "#   #", "#### ", "#  # ", "#   #"];
function drawCrosshair(img: ImageData, w: number, h: number, cx: number, cy: number) { const set = (x: number, y: number, a: number) => { if (x < 0 || y < 0 || x >= w || y >= h) return; const o = (y * w + x) * 4; img.data[o] = Math.round(img.data[o]! * (1 - a) + 220 * a); img.data[o + 1] = Math.round(img.data[o + 1]! * (1 - a) + 220 * a); img.data[o + 2] = Math.round(img.data[o + 2]! * (1 - a) + 200 * a); }; for (let i = 8; i < 18; i++) { set((cx + i) | 0, cy | 0, .35); set((cx - i) | 0, cy | 0, .35); set(cx | 0, (cy + i) | 0, .35); set(cx | 0, (cy - i) | 0, .35); } }
