import type { Patient, Projection, SimPose, TubeState, ExposureState, RadiographResult } from "./types";
import { sampleAnatomy, hashPatient, type Paths, type SampleCtx } from "./anatomy";
import { addSharedOrganPaths } from "./shared-anatomy-sampling";
import { addSharedTissueLayers } from "./shared-tissue-sampling";
import { samplePaChest } from "./pa-chest-model";
import { buildMetrics, fieldScatter, incidentFluence, partThickness } from "./exposure";
import { clamp, fbm } from "./geometry";
import { projectionGeometry } from "./projection-physics";
import { createPrimaryBeamModel, type MaterialPath, type RadiographicMaterial } from "./nist-attenuation";
import { projectAtlasTissuePaths, type AtlasTissueMaterialPaths } from "./atlas-tissue-projector";
import { projectAtlasSkeletalPaths, type AtlasSkeletalMaterialPaths } from "./atlas-skeletal-projector";
import { canonicalAtlasMaterialProjection, usesCanonicalAtlasProjection } from "./canonical-atlas-projection";
import { fullBodyVoxelPhantom } from "./full-body-voxel-phantom";
import { integrateMaterialVolume } from "./voxel-volume-projector";
import { loadPatientAnatomy,projectPatientVolumeRay } from "./patient-anatomy";
import { scoreExposure } from "./scoring";
import type { PathologyId } from "./requests";
function pathsToMaterials(p:Paths):MaterialPath{return{air:Math.max(0,p.air+p.gas*40),inflatedLung:Math.max(0,p.lung),adipose:Math.max(0,p.fat),soft:Math.max(0,p.soft*1.05),trabecularBone:Math.max(0,p.bone),corticalBone:Math.max(0,p.cortical),metal:Math.max(0,p.metal)};}
function ellipse(x:number,y:number,cx:number,cy:number,rx:number,ry:number){const q=((x-cx)/rx)**2+((y-cy)/ry)**2;return q<1?1-q:0;}
function removePath(paths:MaterialPath,amount:number,order:readonly RadiographicMaterial[]){let left=Math.max(0,amount),removed=0;for(const material of order){const current=Math.max(0,paths[material]??0),take=Math.min(current,left);paths[material]=current-take;left-=take;removed+=take;if(left<=0)break;}return removed;}
function addPath(paths:MaterialPath,m:RadiographicMaterial,a:number){if(a>0)paths[m]=(paths[m]??0)+a;}
function applyPathologyMaterials(paths:MaterialPath,id:PathologyId,x:number,y:number,p:Projection){if(p.anatomy!=="torso-ap"&&p.anatomy!=="torso-lat")return;if(id==="consolidation"){const q=.95*ellipse(x,y,-5.5,43,5.5,6),r=removePath(paths,4.5*q,["inflatedLung","air"]);addPath(paths,"soft",r*.72);addPath(paths,"blood",r*.28);}else if(id==="pneumothorax"){const q=.95*ellipse(x,y,-8.5,32,5.5,8),r=removePath(paths,6*q,["inflatedLung","soft","muscle","blood"]);addPath(paths,"air",r);}}
function atlasTissueAt(m:AtlasTissueMaterialPaths,i:number):MaterialPath{return{adipose:m.adipose[i]!,muscle:m.muscle[i]!,soft:m.soft[i]!,inflatedLung:m.inflatedLung[i]!,blood:m.blood[i]!,brain:m.brain[i]!,air:m.air[i]!};}
function mergeSkeletal(p:MaterialPath,m:AtlasSkeletalMaterialPaths,i:number){removePath(p,m.displacedSoft[i]!,["soft","muscle","adipose","inflatedLung","blood","brain","air"]);addPath(p,"corticalBone",m.corticalBone[i]!);addPath(p,"trabecularBone",m.trabecularBone[i]!);addPath(p,"adipose",m.adipose[i]!);}
function totalPath(p:MaterialPath){let n=0;for(const[k,v]of Object.entries(p)as[RadiographicMaterial,number][])if(k!=="air")n+=Math.max(0,v??0);return n;}
function localCoords(projection:Projection,patient:Patient,pose:SimPose,px:number,py:number,w:number,h:number,tube:TubeState,geometry:ReturnType<typeof projectionGeometry>){const cmX=((px+.5)/w-.5)*tube.collimationW/geometry.magnification,cmY=((py+.5)/h-.5)*tube.collimationH/geometry.magnification,ry=cmY-Math.tan(tube.angle*Math.PI/180)*geometry.oidCm;if(projection.anatomy==="torso-ap"||projection.anatomy==="shoulder-ap"||projection.anatomy==="full-body-ap")return{x:tube.crX+cmX*Math.cos(pose.rotationY*Math.PI/180),y:tube.crY+ry};return{x:tube.crX+cmX,y:tube.crY+ry};}
function blur(src:Float32Array,w:number,h:number,r:number){let cur=new Float32Array(src);for(let p=0;p<r;p++){const o=new Float32Array(src.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,n=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=Math.max(0,Math.min(w-1,x+dx)),yy=Math.max(0,Math.min(h-1,y+dy)),wt=!dx&&!dy?4:dx===0||dy===0?2:1;s+=cur[yy*w+xx]!*wt;n+=wt;}o[y*w+x]=s/n;}cur=o;}return cur;}
function percentile(a:number[],q:number){if(!a.length)return 0;a.sort((x,y)=>x-y);return a[Math.round((a.length-1)*q)]!;}
export function preloadRadiographAssets(_p:Projection[]){}
export async function renderRadiograph(args:{patient:Patient;projection:Projection;pose:SimPose;tube:TubeState;exposure:ExposureState;pathologyId?:PathologyId;caseId?:string|null;width?:number;height?:number;}):Promise<RadiographResult>{
 const{patient,projection,pose,tube,exposure,pathologyId="none",caseId}=args;try{const aspect=tube.collimationW/tube.collimationH,height=args.height??768,width=args.width??Math.max(128,Math.round(height*aspect)),n=width*height;if(width<64||height<64)throw new Error("Render failed — detector matrix too small.");
 const geometry=projectionGeometry(projection,tube,pose,exposure.focalSpot),beam=createPrimaryBeamModel(exposure.kvp),I0=incidentFluence(exposure.kvp,exposure.mas,tube.sid,exposure.grid),scatterFrac=fieldScatter(tube.collimationW,tube.collimationH,partThickness(patient,projection),exposure.grid),seed=hashPatient(patient.id),ctx:SampleCtx={patient,projection,pose,seed},anatomy=await loadPatientAnatomy(patient,caseId),whole=projection.id==="ap-full-body",canonical=usesCanonicalAtlasProjection(projection),phantom=!anatomy&&whole?fullBodyVoxelPhantom(patient):null;
 let atlasTissue:AtlasTissueMaterialPaths|null=null,atlasBone:AtlasSkeletalMaterialPaths|null=null,atlasMask:Float32Array|null=null;if(!anatomy&&!whole)try{if(canonical){const m=await canonicalAtlasMaterialProjection({patient,projection,tube,width,height,geometry});atlasTissue=m.tissue;atlasBone=m.skeletal;atlasMask=m.tissueMask;}else{[atlasBone,atlasTissue]=await Promise.all([projectAtlasSkeletalPaths({patient,projection,pose,tube,width,height,geometry,wholeBody:false}),projectAtlasTissuePaths({patient,projection,tube,width,height,geometry,wholeBody:false})]);}}catch(e){console.warn("Fallback atlas projection failed",e);}
 const signal=new Float32Array(n),detector=new Float32Array(n),body=new Float32Array(n);let sum=0;for(let py=0;py<height;py++)for(let px=0;px<width;px++){const i=py*width+px,{x,y}=localCoords(projection,patient,pose,px,py,width,height,tube,geometry);let paths:MaterialPath;
 if(anatomy){paths=projectPatientVolumeRay({anatomy,projection,pose,tube,geometry,detectorXcm:x,detectorYcm:y});}
 else if(whole&&phantom){const sourceZ=-Math.max(80,tube.sid/geometry.magnification),rayZ=-sourceZ;paths=integrateMaterialVolume(phantom,{originCm:[0,tube.crY,sourceZ],direction:[x,y-tube.crY,rayZ]});}
 else{const procedural=projection.id==="pa-chest"?samplePaChest(x,y,patient,pose,seed):sampleAnatomy(x,y,ctx);if(projection.anatomy==="torso-ap"||projection.anatomy==="torso-lat"){addSharedTissueLayers(procedural,x,y,patient,pose,projection);addSharedOrganPaths(procedural,x,y,patient,pose);}paths=pathsToMaterials(procedural);if(atlasTissue&&(!atlasMask||(atlasMask[i]??1)>.5))paths=atlasTissueAt(atlasTissue,i);if(atlasBone)mergeSkeletal(paths,atlasBone,i);applyPathologyMaterials(paths,pathologyId,x,y,projection);}
 const od=beam.opticalDepth(paths),occupied=totalPath(paths),bw=clamp(occupied/.8,0,1);body[i]=bw;const primary=I0*beam.transmission(paths),scatter=I0*scatterFrac*bw*(.0015+.006*(1-Math.exp(-od*.45))),air=I0*1.02,s=air*(1-bw)+(primary+scatter)*bw;signal[i]=s;sum+=s;}
 const airRef=I0*1.02,samples:number[]=[];for(let i=0;i<n;i++){detector[i]=Math.max(0,-Math.log(clamp(signal[i]!/airRef,1e-6,1.02)));if(body[i]>.4)samples.push(detector[i]!);}const lo=percentile([...samples],.03),mid=percentile([...samples],.55),hi=Math.max(mid+.12,percentile([...samples],.995)),fine=blur(detector,width,height,1),broad=blur(detector,width,height,5),canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const g=canvas.getContext("2d");if(!g)throw new Error("No canvas context");const img=g.createImageData(width,height);let noiseAcc=0,contrastAcc=0;
 for(let i=0;i<n;i++){const x=i%width,y=i/width|0,bw=body[i]!,d=detector[i]!;let t=d<=mid?.08+.40*Math.pow(clamp((d-lo)/Math.max(.03,mid-lo),0,1),.82):.48+.36*Math.pow(clamp((d-mid)/(hi-mid),0,1),.78);t+=(d-fine[i]!)*.08+(fine[i]!-broad[i]!)*.12;const noise=(fbm(x*.61,y*.61,seed+4)-.5)*(.002+.0025/Math.sqrt(Math.max(.6,exposure.mas)))*bw;t=clamp(.025*(1-bw)+t*bw+noise,.02,.96);noiseAcc+=Math.abs(noise);contrastAcc+=Math.abs(d-broad[i]!);const v=Math.round(t*255),j=i*4;img.data[j]=v;img.data[j+1]=v;img.data[j+2]=v;img.data[j+3]=255;}
 g.putImageData(img,0,0);const metrics=buildMetrics({patient,projection,pose,tube,exposure,meanSignal:sum/n,noise:noiseAcc/n,contrast:contrastAcc/n,scatterFrac}),score=scoreExposure({patient,projection,pose,tube,exposure,metrics});return{dataUrl:canvas.toDataURL("image/png"),metrics,...score};}catch(err){throw err instanceof Error?err:new Error(String(err));}}
